package org.cagrid.delegatedcredential.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.delegatedcredential.wsrf.stubs.DelegatedCredentialPortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:48.098-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "DelegatedCredentialService", 
                  wsdlLocation = "/schema/org/cagrid/cds/DelegatedCredential_service.wsdl",
                  targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/service") 
public class DelegatedCredentialService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/service", "DelegatedCredentialService");
    public final static QName DelegatedCredentialPortTypePort = new QName("http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/service", "DelegatedCredentialPortTypePort");
    static {
        URL url = DelegatedCredentialService.class.getResource("/schema/org/cagrid/cds/DelegatedCredential_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DelegatedCredentialService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/cds/DelegatedCredential_service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DelegatedCredentialService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DelegatedCredentialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DelegatedCredentialService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DelegatedCredentialPortType
     */
    @WebEndpoint(name = "DelegatedCredentialPortTypePort")
    public DelegatedCredentialPortType getDelegatedCredentialPortTypePort() {
        return super.getPort(DelegatedCredentialPortTypePort, DelegatedCredentialPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DelegatedCredentialPortType
     */
    @WebEndpoint(name = "DelegatedCredentialPortTypePort")
    public DelegatedCredentialPortType getDelegatedCredentialPortTypePort(WebServiceFeature... features) {
        return super.getPort(DelegatedCredentialPortTypePort, DelegatedCredentialPortType.class, features);
    }

}
