package org.cagrid.gts.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.gts.wsrf.stubs.GTSPortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-03T15:36:59.743-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "GTSService", 
                  wsdlLocation = "/schema/org/cagrid/gts/GTS_service.wsdl",
                  targetNamespace = "http://cagrid.nci.nih.gov/GTS/service") 
public class GTSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cagrid.nci.nih.gov/GTS/service", "GTSService");
    public final static QName GTSPortTypePort = new QName("http://cagrid.nci.nih.gov/GTS/service", "GTSPortTypePort");
    static {
        URL url = GTSService.class.getResource("/schema/org/cagrid/gts/GTS_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GTSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/gts/GTS_service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GTSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GTSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GTSPortType
     */
    @WebEndpoint(name = "GTSPortTypePort")
    public GTSPortType getGTSPortTypePort() {
        return super.getPort(GTSPortTypePort, GTSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GTSPortType
     */
    @WebEndpoint(name = "GTSPortTypePort")
    public GTSPortType getGTSPortTypePort(WebServiceFeature... features) {
        return super.getPort(GTSPortTypePort, GTSPortType.class, features);
    }

}
