
package org.cagrid.cds.wsrf.stubs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.cagrid.cds.wsrf.service.CredentialDelegationService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:47.180-04:00
 * Generated source version: 2.6.3
 * 
 */
public final class CredentialDelegationServicePortType_CredentialDelegationServicePortTypePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cds.gaards.cagrid.org/CredentialDelegationService/service", "CredentialDelegationService");

    private CredentialDelegationServicePortType_CredentialDelegationServicePortTypePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CredentialDelegationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CredentialDelegationService ss = new CredentialDelegationService(wsdlURL, SERVICE_NAME);
        CredentialDelegationServicePortType port = ss.getCredentialDelegationServicePortTypePort();  
        
        {
        System.out.println("Invoking deleteDelegatedCredential...");
        DeleteDelegatedCredentialRequest _deleteDelegatedCredential_parameters = null;
        try {
            DeleteDelegatedCredentialResponse _deleteDelegatedCredential__return = port.deleteDelegatedCredential(_deleteDelegatedCredential_parameters);
            System.out.println("deleteDelegatedCredential.result=" + _deleteDelegatedCredential__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking approveDelegation...");
        ApproveDelegationRequest _approveDelegation_parameters = null;
        try {
            ApproveDelegationResponse _approveDelegation__return = port.approveDelegation(_approveDelegation_parameters);
            System.out.println("approveDelegation.result=" + _approveDelegation__return);

        } catch (DelegationFaultFaultMessage e) { 
            System.out.println("Expected exception: DelegationFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryResourceProperties...");
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties _queryResourceProperties_queryResourcePropertiesRequest = null;
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _queryResourceProperties__return = port.queryResourceProperties(_queryResourceProperties_queryResourcePropertiesRequest);
            System.out.println("queryResourceProperties.result=" + _queryResourceProperties__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault e) { 
            System.out.println("Expected exception: QueryEvaluationErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault e) { 
            System.out.println("Expected exception: UnknownQueryExpressionDialectFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault e) { 
            System.out.println("Expected exception: InvalidQueryExpressionFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findDelegatedCredentials...");
        FindDelegatedCredentialsRequest _findDelegatedCredentials_parameters = null;
        try {
            FindDelegatedCredentialsResponse _findDelegatedCredentials__return = port.findDelegatedCredentials(_findDelegatedCredentials_parameters);
            System.out.println("findDelegatedCredentials.result=" + _findDelegatedCredentials__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addAdmin...");
        AddAdminRequest _addAdmin_parameters = null;
        try {
            AddAdminResponse _addAdmin__return = port.addAdmin(_addAdmin_parameters);
            System.out.println("addAdmin.result=" + _addAdmin__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getResourceProperty...");
        QName _getResourceProperty_getResourcePropertyRequest = new QName("", "");
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _getResourceProperty__return = port.getResourceProperty(_getResourceProperty_getResourcePropertyRequest);
            System.out.println("getResourceProperty.result=" + _getResourceProperty__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking findCredentialsDelegatedToClient...");
        FindCredentialsDelegatedToClientRequest _findCredentialsDelegatedToClient_parameters = null;
        try {
            FindCredentialsDelegatedToClientResponse _findCredentialsDelegatedToClient__return = port.findCredentialsDelegatedToClient(_findCredentialsDelegatedToClient_parameters);
            System.out.println("findCredentialsDelegatedToClient.result=" + _findCredentialsDelegatedToClient__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking removeAdmin...");
        RemoveAdminRequest _removeAdmin_parameters = null;
        try {
            RemoveAdminResponse _removeAdmin__return = port.removeAdmin(_removeAdmin_parameters);
            System.out.println("removeAdmin.result=" + _removeAdmin__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMultipleResourceProperties...");
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties _getMultipleResourceProperties_getMultipleResourcePropertiesRequest = null;
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _getMultipleResourceProperties__return = port.getMultipleResourceProperties(_getMultipleResourceProperties_getMultipleResourcePropertiesRequest);
            System.out.println("getMultipleResourceProperties.result=" + _getMultipleResourceProperties__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking searchDelegatedCredentialAuditLog...");
        SearchDelegatedCredentialAuditLogRequest _searchDelegatedCredentialAuditLog_parameters = null;
        try {
            SearchDelegatedCredentialAuditLogResponse _searchDelegatedCredentialAuditLog__return = port.searchDelegatedCredentialAuditLog(_searchDelegatedCredentialAuditLog_parameters);
            System.out.println("searchDelegatedCredentialAuditLog.result=" + _searchDelegatedCredentialAuditLog__return);

        } catch (DelegationFaultFaultMessage e) { 
            System.out.println("Expected exception: DelegationFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getServiceSecurityMetadata...");
        org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest _getServiceSecurityMetadata_parameters = null;
        org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _getServiceSecurityMetadata__return = port.getServiceSecurityMetadata(_getServiceSecurityMetadata_parameters);
        System.out.println("getServiceSecurityMetadata.result=" + _getServiceSecurityMetadata__return);


        }
        {
        System.out.println("Invoking updateDelegatedCredentialStatus...");
        UpdateDelegatedCredentialStatusRequest _updateDelegatedCredentialStatus_parameters = null;
        try {
            UpdateDelegatedCredentialStatusResponse _updateDelegatedCredentialStatus__return = port.updateDelegatedCredentialStatus(_updateDelegatedCredentialStatus_parameters);
            System.out.println("updateDelegatedCredentialStatus.result=" + _updateDelegatedCredentialStatus__return);

        } catch (DelegationFaultFaultMessage e) { 
            System.out.println("Expected exception: DelegationFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAdmins...");
        GetAdminsRequest _getAdmins_parameters = null;
        try {
            GetAdminsResponse _getAdmins__return = port.getAdmins(_getAdmins_parameters);
            System.out.println("getAdmins.result=" + _getAdmins__return);

        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking initiateDelegation...");
        InitiateDelegationRequest _initiateDelegation_parameters = null;
        try {
            InitiateDelegationResponse _initiateDelegation__return = port.initiateDelegation(_initiateDelegation_parameters);
            System.out.println("initiateDelegation.result=" + _initiateDelegation__return);

        } catch (InvalidPolicyFaultFaultMessage e) { 
            System.out.println("Expected exception: InvalidPolicyFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (DelegationFaultFaultMessage e) { 
            System.out.println("Expected exception: DelegationFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (CDSInternalFaultFaultMessage e) { 
            System.out.println("Expected exception: CDSInternalFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (PermissionDeniedFaultFaultMessage e) { 
            System.out.println("Expected exception: PermissionDeniedFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
