package org.cagrid.cds.wsrf.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:47.297-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", name = "CredentialDelegationServicePortType")
@XmlSeeAlso({gov.nih.nci.cagrid.metadata.ObjectFactory.class, org.cagrid.gaards.security.servicesecurity.ObjectFactory.class, ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.xmlsoap.schemas.ws._2004._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class, org.cagrid.delegatedcredential.types.ObjectFactory.class, gov.nih.nci.cagrid.metadata.security.ObjectFactory.class, org.cagrid.cds.model.ObjectFactory.class, gov.nih.nci.cagrid.metadata.common.ObjectFactory.class, org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ObjectFactory.class, org.cagrid.cds.types.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01.ObjectFactory.class, gov.nih.nci.cagrid.metadata.service.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CredentialDelegationServicePortType {

    @WebResult(name = "DeleteDelegatedCredentialResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/DeleteDelegatedCredentialRequest")
    public DeleteDelegatedCredentialResponse deleteDelegatedCredential(
            @WebParam(partName = "parameters", name = "DeleteDelegatedCredentialRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            DeleteDelegatedCredentialRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "ApproveDelegationResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/ApproveDelegationRequest")
    public ApproveDelegationResponse approveDelegation(
            @WebParam(partName = "parameters", name = "ApproveDelegationRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            ApproveDelegationRequest parameters
    ) throws DelegationFaultFaultMessage, CDSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "QueryResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "QueryResourcePropertiesResponse")
    @WebMethod(operationName = "QueryResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/QueryResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(
            @WebParam(partName = "QueryResourcePropertiesRequest", name = "QueryResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "FindDelegatedCredentialsResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/FindDelegatedCredentialsRequest")
    public FindDelegatedCredentialsResponse findDelegatedCredentials(
            @WebParam(partName = "parameters", name = "FindDelegatedCredentialsRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            FindDelegatedCredentialsRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "AddAdminResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/AddAdminRequest")
    public AddAdminResponse addAdmin(
            @WebParam(partName = "parameters", name = "AddAdminRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            AddAdminRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "GetResourcePropertyResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetResourcePropertyResponse")
    @WebMethod(operationName = "GetResourceProperty", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetResourceProperty")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(
            @WebParam(partName = "GetResourcePropertyRequest", name = "GetResourceProperty", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            javax.xml.namespace.QName getResourcePropertyRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "FindCredentialsDelegatedToClientResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/FindCredentialsDelegatedToClientRequest")
    public FindCredentialsDelegatedToClientResponse findCredentialsDelegatedToClient(
            @WebParam(partName = "parameters", name = "FindCredentialsDelegatedToClientRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            FindCredentialsDelegatedToClientRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "RemoveAdminResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/RemoveAdminRequest")
    public RemoveAdminResponse removeAdmin(
            @WebParam(partName = "parameters", name = "RemoveAdminRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            RemoveAdminRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "GetMultipleResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetMultipleResourcePropertiesResponse")
    @WebMethod(operationName = "GetMultipleResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetMultipleResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(
            @WebParam(partName = "GetMultipleResourcePropertiesRequest", name = "GetMultipleResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "SearchDelegatedCredentialAuditLogResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/SearchDelegatedCredentialAuditLogRequest")
    public SearchDelegatedCredentialAuditLogResponse searchDelegatedCredentialAuditLog(
            @WebParam(partName = "parameters", name = "SearchDelegatedCredentialAuditLogRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            SearchDelegatedCredentialAuditLogRequest parameters
    ) throws DelegationFaultFaultMessage, CDSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "GetServiceSecurityMetadataResponse", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity", partName = "parameters")
    @WebMethod(action = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity/GetServiceSecurityMetadataRequest")
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(
            @WebParam(partName = "parameters", name = "GetServiceSecurityMetadataRequest", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity")
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters
    );

    @WebResult(name = "UpdateDelegatedCredentialStatusResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/UpdateDelegatedCredentialStatusRequest")
    public UpdateDelegatedCredentialStatusResponse updateDelegatedCredentialStatus(
            @WebParam(partName = "parameters", name = "UpdateDelegatedCredentialStatusRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            UpdateDelegatedCredentialStatusRequest parameters
    ) throws DelegationFaultFaultMessage, CDSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "GetAdminsResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/GetAdminsRequest")
    public GetAdminsResponse getAdmins(
            @WebParam(partName = "parameters", name = "GetAdminsRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            GetAdminsRequest parameters
    ) throws PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;

    @WebResult(name = "InitiateDelegationResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/InitiateDelegationRequest")
    public InitiateDelegationResponse initiateDelegation(
            @WebParam(partName = "parameters", name = "InitiateDelegationRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService")
            InitiateDelegationRequest parameters
    ) throws InvalidPolicyFaultFaultMessage, DelegationFaultFaultMessage, CDSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage;
}
