
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cagrid.cds.wsrf.stubs;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:47.276-04:00
 * Generated source version: 2.6.3
 * 
 */

@WebService(
                      serviceName = "CredentialDelegationService",
                      portName = "CredentialDelegationServicePortTypePort",
                      targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/service",
                      wsdlLocation = "/schema/org/cagrid/cds/CredentialDelegationService_service.wsdl",
                      endpointInterface = "org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType")
                      
public class CredentialDelegationServicePortTypeImpl implements CredentialDelegationServicePortType {

    private static final Logger LOG = Logger.getLogger(CredentialDelegationServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#deleteDelegatedCredential(org.cagrid.cds.wsrf.stubs.DeleteDelegatedCredentialRequest  parameters )*
     */
    public DeleteDelegatedCredentialResponse deleteDelegatedCredential(DeleteDelegatedCredentialRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    {
        LOG.info("Executing operation deleteDelegatedCredential");
        System.out.println(parameters);
        try {
            DeleteDelegatedCredentialResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#approveDelegation(org.cagrid.cds.wsrf.stubs.ApproveDelegationRequest  parameters )*
     */
    public ApproveDelegationResponse approveDelegation(ApproveDelegationRequest parameters) throws DelegationFaultFaultMessage , CDSInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage    {
        LOG.info("Executing operation approveDelegation");
        System.out.println(parameters);
        try {
            ApproveDelegationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DelegationFaultFaultMessage("DelegationFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties  queryResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation queryResourceProperties");
        System.out.println(queryResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault("QueryEvaluationErrorFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault("UnknownQueryExpressionDialectFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault("InvalidQueryExpressionFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#findDelegatedCredentials(org.cagrid.cds.wsrf.stubs.FindDelegatedCredentialsRequest  parameters )*
     */
    public FindDelegatedCredentialsResponse findDelegatedCredentials(FindDelegatedCredentialsRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    {
        LOG.info("Executing operation findDelegatedCredentials");
        System.out.println(parameters);
        try {
            FindDelegatedCredentialsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#addAdmin(org.cagrid.cds.wsrf.stubs.AddAdminRequest  parameters )*
     */
    public AddAdminResponse addAdmin(AddAdminRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    {
        LOG.info("Executing operation addAdmin");
        System.out.println(parameters);
        try {
            AddAdminResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#findCredentialsDelegatedToClient(org.cagrid.cds.wsrf.stubs.FindCredentialsDelegatedToClientRequest  parameters )*
     */
    public org.cagrid.cds.wsrf.stubs.FindCredentialsDelegatedToClientResponse findCredentialsDelegatedToClient(FindCredentialsDelegatedToClientRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    { 
        LOG.info("Executing operation findCredentialsDelegatedToClient");
        System.out.println(parameters);
        try {
            org.cagrid.cds.wsrf.stubs.FindCredentialsDelegatedToClientResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#removeAdmin(org.cagrid.cds.wsrf.stubs.RemoveAdminRequest  parameters )*
     */
    public RemoveAdminResponse removeAdmin(RemoveAdminRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    {
        LOG.info("Executing operation removeAdmin");
        System.out.println(parameters);
        try {
            RemoveAdminResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties  getMultipleResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getMultipleResourceProperties");
        System.out.println(getMultipleResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#searchDelegatedCredentialAuditLog(org.cagrid.cds.wsrf.stubs.SearchDelegatedCredentialAuditLogRequest  parameters )*
     */
    public org.cagrid.cds.wsrf.stubs.SearchDelegatedCredentialAuditLogResponse searchDelegatedCredentialAuditLog(SearchDelegatedCredentialAuditLogRequest parameters) throws DelegationFaultFaultMessage , CDSInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage    { 
        LOG.info("Executing operation searchDelegatedCredentialAuditLog");
        System.out.println(parameters);
        try {
            org.cagrid.cds.wsrf.stubs.SearchDelegatedCredentialAuditLogResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DelegationFaultFaultMessage("DelegationFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest  parameters )*
     */
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters) { 
        LOG.info("Executing operation getServiceSecurityMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#updateDelegatedCredentialStatus(org.cagrid.cds.wsrf.stubs.UpdateDelegatedCredentialStatusRequest  parameters )*
     */
    public org.cagrid.cds.wsrf.stubs.UpdateDelegatedCredentialStatusResponse updateDelegatedCredentialStatus(UpdateDelegatedCredentialStatusRequest parameters) throws DelegationFaultFaultMessage , CDSInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage    { 
        LOG.info("Executing operation updateDelegatedCredentialStatus");
        System.out.println(parameters);
        try {
            org.cagrid.cds.wsrf.stubs.UpdateDelegatedCredentialStatusResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DelegationFaultFaultMessage("DelegationFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#getAdmins(org.cagrid.cds.wsrf.stubs.GetAdminsRequest  parameters )*
     */
    public GetAdminsResponse getAdmins(GetAdminsRequest parameters) throws PermissionDeniedFaultFaultMessage , CDSInternalFaultFaultMessage    {
        LOG.info("Executing operation getAdmins");
        System.out.println(parameters);
        try {
            GetAdminsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType#initiateDelegation(org.cagrid.cds.wsrf.stubs.InitiateDelegationRequest  parameters )*
     */
    public InitiateDelegationResponse initiateDelegation(InitiateDelegationRequest parameters) throws InvalidPolicyFaultFaultMessage , DelegationFaultFaultMessage , CDSInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage    {
        LOG.info("Executing operation initiateDelegation");
        System.out.println(parameters);
        try {
            InitiateDelegationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidPolicyFaultFaultMessage("InvalidPolicyFaultFaultMessage...");
        //throw new DelegationFaultFaultMessage("DelegationFaultFaultMessage...");
        //throw new CDSInternalFaultFaultMessage("CDSInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

}
