
package org.cagrid.cds.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:47.270-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidPolicyFault", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/types")
public class InvalidPolicyFaultFaultMessage extends Exception {
    
    private org.cagrid.cds.types.InvalidPolicyFault invalidPolicyFault;

    public InvalidPolicyFaultFaultMessage() {
        super();
    }
    
    public InvalidPolicyFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidPolicyFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPolicyFaultFaultMessage(String message, org.cagrid.cds.types.InvalidPolicyFault invalidPolicyFault) {
        super(message);
        this.invalidPolicyFault = invalidPolicyFault;
    }

    public InvalidPolicyFaultFaultMessage(String message, org.cagrid.cds.types.InvalidPolicyFault invalidPolicyFault, Throwable cause) {
        super(message, cause);
        this.invalidPolicyFault = invalidPolicyFault;
    }

    public org.cagrid.cds.types.InvalidPolicyFault getFaultInfo() {
        return this.invalidPolicyFault;
    }
}
