<?xml version="1.0" encoding="UTF-8"?>
<!--
Portions of this file Copyright 1999-2005 University of Chicago
Portions of this file Copyright 1999-2005 The University of Southern California.

This file or a portion of this file is licensed under the
terms of the Globus Toolkit Public License, found at
http://www.globus.org/toolkit/download/license.html.
If you redistribute this file, with or without
modifications, you must include this notice in the file.
-->
<wsdl:definitions name="ServiceGroupFactory" targetNamespace="http://mds.globus.org/2004/10/servicegroupfactory/bindings" xmlns:porttype="http://mds.globus.org/2004/10/servicegroupfactory" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://mds.globus.org/2004/10/servicegroupfactory" location="factory_port_type.wsdl"/>
  <wsdl:binding name="ServiceGroupFactoryPortTypeSOAPBinding" type="porttype:ServiceGroupFactoryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="create">
      <soap:operation soapAction="http://mds.globus.org/2004/10/servicegroupfactory/ServiceGroupFactoryPortType/createRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="CreateServiceGroupFault">
        <soap:fault name="CreateServiceGroupFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
