<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="gluerpconfigwrapper" targetNamespace="null/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="null/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="null/bindings" location="gluerpconfigwrapper_bindings.wsdl"/>
  <wsdl:service name="gluerpconfigwrapperService">
  </wsdl:service>
</wsdl:definitions>
