<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="rpproviderwrapper" targetNamespace="null/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="rpproviderwrapper.wsdl"/>
</wsdl:definitions>
