package org.cagrid.cds.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.cds.wsrf.stubs.CredentialDelegationServicePortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:47.308-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "CredentialDelegationService", 
                  wsdlLocation = "/schema/org/cagrid/cds/CredentialDelegationService_service.wsdl",
                  targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/service") 
public class CredentialDelegationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cds.gaards.cagrid.org/CredentialDelegationService/service", "CredentialDelegationService");
    public final static QName CredentialDelegationServicePortTypePort = new QName("http://cds.gaards.cagrid.org/CredentialDelegationService/service", "CredentialDelegationServicePortTypePort");
    static {
        URL url = CredentialDelegationService.class.getResource("/schema/org/cagrid/cds/CredentialDelegationService_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CredentialDelegationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/cds/CredentialDelegationService_service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CredentialDelegationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CredentialDelegationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CredentialDelegationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CredentialDelegationServicePortType
     */
    @WebEndpoint(name = "CredentialDelegationServicePortTypePort")
    public CredentialDelegationServicePortType getCredentialDelegationServicePortTypePort() {
        return super.getPort(CredentialDelegationServicePortTypePort, CredentialDelegationServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CredentialDelegationServicePortType
     */
    @WebEndpoint(name = "CredentialDelegationServicePortTypePort")
    public CredentialDelegationServicePortType getCredentialDelegationServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(CredentialDelegationServicePortTypePort, CredentialDelegationServicePortType.class, features);
    }

}
