package org.cagrid.gridgrouper.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.gridgrouper.wsrf.stubs.GridGrouperPortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.189-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "GridGrouperService", 
                  wsdlLocation = "/schema/org/cagrid/gridgrouper/GridGrouper_Service.wsdl",
                  targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/service") 
public class GridGrouperService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cagrid.nci.nih.gov/GridGrouper/service", "GridGrouperService");
    public final static QName GridGrouperPortTypePort = new QName("http://cagrid.nci.nih.gov/GridGrouper/service", "GridGrouperPortTypePort");
    static {
        URL url = GridGrouperService.class.getResource("/schema/org/cagrid/gridgrouper/GridGrouper_Service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GridGrouperService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/gridgrouper/GridGrouper_Service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GridGrouperService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GridGrouperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GridGrouperService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GridGrouperPortType
     */
    @WebEndpoint(name = "GridGrouperPortTypePort")
    public GridGrouperPortType getGridGrouperPortTypePort() {
        return super.getPort(GridGrouperPortTypePort, GridGrouperPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GridGrouperPortType
     */
    @WebEndpoint(name = "GridGrouperPortTypePort")
    public GridGrouperPortType getGridGrouperPortTypePort(WebServiceFeature... features) {
        return super.getPort(GridGrouperPortTypePort, GridGrouperPortType.class, features);
    }

}
