
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cagrid.mms.wsrf.stubs;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2014-01-23T21:08:48.039-05:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "MetadataModelService",
                      portName = "MetadataModelServicePortTypePort",
                      targetNamespace = "http://mms.cagrid.org/MetadataModelService/service",
                      wsdlLocation = "/schema/org/cagrid/mms/MetadataModelService_service.wsdl",
                      endpointInterface = "org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType")
                      
public class MetadataModelServicePortTypeImpl implements MetadataModelServicePortType {

    private static final Logger LOG = Logger.getLogger(MetadataModelServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties  queryResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault    { 
        LOG.info("Executing operation queryResourceProperties");
        System.out.println(queryResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault("QueryEvaluationErrorFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault("InvalidQueryExpressionFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault("UnknownQueryExpressionDialectFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#generateDomainModelForClassesWithExcludes(org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesWithExcludesRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesWithExcludesResponse generateDomainModelForClassesWithExcludes(GenerateDomainModelForClassesWithExcludesRequest parameters) throws InvalidUMLProjectIndentifierFaultMessage    { 
        LOG.info("Executing operation generateDomainModelForClassesWithExcludes");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesWithExcludesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidUMLProjectIndentifierFaultMessage("InvalidUMLProjectIndentifierFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#generateDomainModelForProject(org.cagrid.mms.wsrf.stubs.GenerateDomainModelForProjectRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.GenerateDomainModelForProjectResponse generateDomainModelForProject(GenerateDomainModelForProjectRequest parameters) throws InvalidUMLProjectIndentifierFaultMessage    { 
        LOG.info("Executing operation generateDomainModelForProject");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.GenerateDomainModelForProjectResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidUMLProjectIndentifierFaultMessage("InvalidUMLProjectIndentifierFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#getModelSourceMetadata(org.cagrid.mms.wsrf.stubs.GetModelSourceMetadataRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.GetModelSourceMetadataResponse getModelSourceMetadata(GetModelSourceMetadataRequest parameters) { 
        LOG.info("Executing operation getModelSourceMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.GetModelSourceMetadataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#generateDomainModelForClasses(org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesResponse generateDomainModelForClasses(GenerateDomainModelForClassesRequest parameters) throws InvalidUMLProjectIndentifierFaultMessage    { 
        LOG.info("Executing operation generateDomainModelForClasses");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.GenerateDomainModelForClassesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidUMLProjectIndentifierFaultMessage("InvalidUMLProjectIndentifierFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#generateDomainModelForPackages(org.cagrid.mms.wsrf.stubs.GenerateDomainModelForPackagesRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.GenerateDomainModelForPackagesResponse generateDomainModelForPackages(GenerateDomainModelForPackagesRequest parameters) throws InvalidUMLProjectIndentifierFaultMessage    { 
        LOG.info("Executing operation generateDomainModelForPackages");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.GenerateDomainModelForPackagesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidUMLProjectIndentifierFaultMessage("InvalidUMLProjectIndentifierFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties  getMultipleResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault    { 
        LOG.info("Executing operation getMultipleResourceProperties");
        System.out.println(getMultipleResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#annotateServiceMetadata(org.cagrid.mms.wsrf.stubs.AnnotateServiceMetadataRequest  parameters )*
     */
    public org.cagrid.mms.wsrf.stubs.AnnotateServiceMetadataResponse annotateServiceMetadata(AnnotateServiceMetadataRequest parameters) throws InvalidUMLProjectIndentifierFaultMessage    { 
        LOG.info("Executing operation annotateServiceMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.mms.wsrf.stubs.AnnotateServiceMetadataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidUMLProjectIndentifierFaultMessage("InvalidUMLProjectIndentifierFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType#getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest  parameters )*
     */
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters) { 
        LOG.info("Executing operation getServiceSecurityMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
