
package org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2014-05-01T13:50:43.358-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "SetResourcePropertyRequestFailedFault", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
public class SetResourcePropertyRequestFailedFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.SetResourcePropertyRequestFailedFaultType setResourcePropertyRequestFailedFault;

    public SetResourcePropertyRequestFailedFault() {
        super();
    }
    
    public SetResourcePropertyRequestFailedFault(String message) {
        super(message);
    }
    
    public SetResourcePropertyRequestFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SetResourcePropertyRequestFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.SetResourcePropertyRequestFailedFaultType setResourcePropertyRequestFailedFault) {
        super(message);
        this.setResourcePropertyRequestFailedFault = setResourcePropertyRequestFailedFault;
    }

    public SetResourcePropertyRequestFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.SetResourcePropertyRequestFailedFaultType setResourcePropertyRequestFailedFault, Throwable cause) {
        super(message, cause);
        this.setResourcePropertyRequestFailedFault = setResourcePropertyRequestFailedFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.SetResourcePropertyRequestFailedFaultType getFaultInfo() {
        return this.setResourcePropertyRequestFailedFault;
    }
}
