
package org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2014-05-01T13:50:43.349-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "UnableToModifyResourcePropertyFault", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
public class UnableToModifyResourcePropertyFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.UnableToModifyResourcePropertyFaultType unableToModifyResourcePropertyFault;

    public UnableToModifyResourcePropertyFault() {
        super();
    }
    
    public UnableToModifyResourcePropertyFault(String message) {
        super(message);
    }
    
    public UnableToModifyResourcePropertyFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToModifyResourcePropertyFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.UnableToModifyResourcePropertyFaultType unableToModifyResourcePropertyFault) {
        super(message);
        this.unableToModifyResourcePropertyFault = unableToModifyResourcePropertyFault;
    }

    public UnableToModifyResourcePropertyFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.UnableToModifyResourcePropertyFaultType unableToModifyResourcePropertyFault, Throwable cause) {
        super(message, cause);
        this.unableToModifyResourcePropertyFault = unableToModifyResourcePropertyFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.UnableToModifyResourcePropertyFaultType getFaultInfo() {
        return this.unableToModifyResourcePropertyFault;
    }
}
