
package org.cagrid.gts.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-04T12:08:10.944-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "CertificateValidationFault", targetNamespace = "http://cagrid.nci.nih.gov/GTS/types")
public class CertificateValidationFaultFaultMessage extends Exception {
    
    private org.cagrid.gts.types.CertificateValidationFault certificateValidationFault;

    public CertificateValidationFaultFaultMessage() {
        super();
    }
    
    public CertificateValidationFaultFaultMessage(String message) {
        super(message);
    }
    
    public CertificateValidationFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CertificateValidationFaultFaultMessage(String message, org.cagrid.gts.types.CertificateValidationFault certificateValidationFault) {
        super(message);
        this.certificateValidationFault = certificateValidationFault;
    }

    public CertificateValidationFaultFaultMessage(String message, org.cagrid.gts.types.CertificateValidationFault certificateValidationFault, Throwable cause) {
        super(message, cause);
        this.certificateValidationFault = certificateValidationFault;
    }

    public org.cagrid.gts.types.CertificateValidationFault getFaultInfo() {
        return this.certificateValidationFault;
    }
}
