
package org.cagrid.gts.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-03T15:36:59.609-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "GTSInternalFault", targetNamespace = "http://cagrid.nci.nih.gov/GTS/types")
public class GTSInternalFaultFaultMessage extends Exception {
    
    private org.cagrid.gts.types.GTSInternalFault gtsInternalFault;

    public GTSInternalFaultFaultMessage() {
        super();
    }
    
    public GTSInternalFaultFaultMessage(String message) {
        super(message);
    }
    
    public GTSInternalFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public GTSInternalFaultFaultMessage(String message, org.cagrid.gts.types.GTSInternalFault gtsInternalFault) {
        super(message);
        this.gtsInternalFault = gtsInternalFault;
    }

    public GTSInternalFaultFaultMessage(String message, org.cagrid.gts.types.GTSInternalFault gtsInternalFault, Throwable cause) {
        super(message, cause);
        this.gtsInternalFault = gtsInternalFault;
    }

    public org.cagrid.gts.types.GTSInternalFault getFaultInfo() {
        return this.gtsInternalFault;
    }
}
