package org.cagrid.gts.wsrf.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-04T12:08:10.989-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://cagrid.nci.nih.gov/GTS", name = "GTSPortType")
@XmlSeeAlso({gov.nih.nci.cagrid.metadata.ObjectFactory.class, org.cagrid.gts.model.ObjectFactory.class, gov.nih.nci.cagrid.metadata.security.ObjectFactory.class, ObjectFactory.class, org.cagrid.gaards.security.servicesecurity.ObjectFactory.class, gov.nih.nci.cagrid.metadata.common.ObjectFactory.class, org.cagrid.gts.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2004._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class, gov.nih.nci.cagrid.metadata.service.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GTSPortType {

    @WebResult(name = "GetAuthoritiesResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/GetAuthoritiesRequest")
    public GetAuthoritiesResponse getAuthorities(
        @WebParam(partName = "parameters", name = "GetAuthoritiesRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        GetAuthoritiesRequest parameters
    ) throws GTSInternalFaultFaultMessage;

    @WebResult(name = "GetServiceSecurityMetadataResponse", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity", partName = "parameters")
    @WebMethod(action = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity/GetServiceSecurityMetadataRequest")
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(
        @WebParam(partName = "parameters", name = "GetServiceSecurityMetadataRequest", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity")
        org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters
    );

    @WebResult(name = "AddPermissionResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/AddPermissionRequest")
    public AddPermissionResponse addPermission(
        @WebParam(partName = "parameters", name = "AddPermissionRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        AddPermissionRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, IllegalPermissionFaultFaultMessage;

    @WebResult(name = "GetMultipleResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetMultipleResourcePropertiesResponse")
    @WebMethod(operationName = "GetMultipleResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetMultipleResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(
        @WebParam(partName = "GetMultipleResourcePropertiesRequest", name = "GetMultipleResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "UpdateCRLResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/UpdateCRLRequest")
    public UpdateCRLResponse updateCRL(
        @WebParam(partName = "parameters", name = "UpdateCRLRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        UpdateCRLRequest parameters
    ) throws GTSInternalFaultFaultMessage, IllegalTrustedAuthorityFaultFaultMessage, InvalidTrustedAuthorityFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "QueryResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "QueryResourcePropertiesResponse")
    @WebMethod(operationName = "QueryResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/QueryResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(
        @WebParam(partName = "QueryResourcePropertiesRequest", name = "QueryResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault;

    @WebResult(name = "UpdateTrustLevelResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/UpdateTrustLevelRequest")
    public UpdateTrustLevelResponse updateTrustLevel(
        @WebParam(partName = "parameters", name = "UpdateTrustLevelRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        UpdateTrustLevelRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, IllegalTrustLevelFaultFaultMessage, InvalidTrustLevelFaultFaultMessage;

    @WebResult(name = "UpdateAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/UpdateAuthorityRequest")
    public UpdateAuthorityResponse updateAuthority(
        @WebParam(partName = "parameters", name = "UpdateAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        UpdateAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, InvalidAuthorityFaultFaultMessage, IllegalAuthorityFaultFaultMessage;

    @WebResult(name = "AddAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/AddAuthorityRequest")
    public AddAuthorityResponse addAuthority(
        @WebParam(partName = "parameters", name = "AddAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        AddAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, IllegalAuthorityFaultFaultMessage;

    @WebResult(name = "UpdateTrustedAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/UpdateTrustedAuthorityRequest")
    public UpdateTrustedAuthorityResponse updateTrustedAuthority(
        @WebParam(partName = "parameters", name = "UpdateTrustedAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        UpdateTrustedAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, IllegalTrustedAuthorityFaultFaultMessage, InvalidTrustedAuthorityFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "RemoveTrustedAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/RemoveTrustedAuthorityRequest")
    public RemoveTrustedAuthorityResponse removeTrustedAuthority(
        @WebParam(partName = "parameters", name = "RemoveTrustedAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        RemoveTrustedAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, InvalidTrustedAuthorityFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "RemoveAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/RemoveAuthorityRequest")
    public RemoveAuthorityResponse removeAuthority(
        @WebParam(partName = "parameters", name = "RemoveAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        RemoveAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, InvalidAuthorityFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "FindPermissionsResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/FindPermissionsRequest")
    public FindPermissionsResponse findPermissions(
        @WebParam(partName = "parameters", name = "FindPermissionsRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        FindPermissionsRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "AddTrustLevelResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/AddTrustLevelRequest")
    public AddTrustLevelResponse addTrustLevel(
        @WebParam(partName = "parameters", name = "AddTrustLevelRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        AddTrustLevelRequest parameters
    ) throws GTSInternalFaultFaultMessage, IllegalTrustLevelFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "AddTrustedAuthorityResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/AddTrustedAuthorityRequest")
    public AddTrustedAuthorityResponse addTrustedAuthority(
        @WebParam(partName = "parameters", name = "AddTrustedAuthorityRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        AddTrustedAuthorityRequest parameters
    ) throws GTSInternalFaultFaultMessage, IllegalTrustedAuthorityFaultFaultMessage, PermissionDeniedFaultFaultMessage;

    @WebResult(name = "GetResourcePropertyResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetResourcePropertyResponse")
    @WebMethod(operationName = "GetResourceProperty", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetResourceProperty")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(
        @WebParam(partName = "GetResourcePropertyRequest", name = "GetResourceProperty", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
        javax.xml.namespace.QName getResourcePropertyRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "UpdateAuthorityPrioritiesResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/UpdateAuthorityPrioritiesRequest")
    public UpdateAuthorityPrioritiesResponse updateAuthorityPriorities(
        @WebParam(partName = "parameters", name = "UpdateAuthorityPrioritiesRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        UpdateAuthorityPrioritiesRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, IllegalAuthorityFaultFaultMessage;

    @WebResult(name = "RemoveTrustLevelResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/RemoveTrustLevelRequest")
    public RemoveTrustLevelResponse removeTrustLevel(
        @WebParam(partName = "parameters", name = "RemoveTrustLevelRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        RemoveTrustLevelRequest parameters
    ) throws GTSInternalFaultFaultMessage, PermissionDeniedFaultFaultMessage, IllegalTrustLevelFaultFaultMessage, InvalidTrustLevelFaultFaultMessage;

    @WebResult(name = "FindTrustedAuthoritiesResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/FindTrustedAuthoritiesRequest")
    public FindTrustedAuthoritiesResponse findTrustedAuthorities(
        @WebParam(partName = "parameters", name = "FindTrustedAuthoritiesRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        FindTrustedAuthoritiesRequest parameters
    );

    @WebResult(name = "GetTrustLevelsResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/GetTrustLevelsRequest")
    public GetTrustLevelsResponse getTrustLevels(
        @WebParam(partName = "parameters", name = "GetTrustLevelsRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        GetTrustLevelsRequest parameters
    ) throws GTSInternalFaultFaultMessage;

    @WebResult(name = "ValidateResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/ValidateRequest")
    public ValidateResponse validate(
        @WebParam(partName = "parameters", name = "ValidateRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        ValidateRequest parameters
    ) throws GTSInternalFaultFaultMessage, CertificateValidationFaultFaultMessage;

    @WebResult(name = "RevokePermissionResponse", targetNamespace = "http://cagrid.nci.nih.gov/GTS", partName = "parameters")
    @WebMethod(action = "http://cagrid.nci.nih.gov/GTS/RevokePermissionRequest")
    public RevokePermissionResponse revokePermission(
        @WebParam(partName = "parameters", name = "RevokePermissionRequest", targetNamespace = "http://cagrid.nci.nih.gov/GTS")
        RevokePermissionRequest parameters
    ) throws GTSInternalFaultFaultMessage, InvalidPermissionFaultFaultMessage, PermissionDeniedFaultFaultMessage;
}
