
package org.cagrid.gts.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-04T12:08:10.936-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "IllegalAuthorityFault", targetNamespace = "http://cagrid.nci.nih.gov/GTS/types")
public class IllegalAuthorityFaultFaultMessage extends Exception {
    
    private org.cagrid.gts.types.IllegalAuthorityFault illegalAuthorityFault;

    public IllegalAuthorityFaultFaultMessage() {
        super();
    }
    
    public IllegalAuthorityFaultFaultMessage(String message) {
        super(message);
    }
    
    public IllegalAuthorityFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalAuthorityFaultFaultMessage(String message, org.cagrid.gts.types.IllegalAuthorityFault illegalAuthorityFault) {
        super(message);
        this.illegalAuthorityFault = illegalAuthorityFault;
    }

    public IllegalAuthorityFaultFaultMessage(String message, org.cagrid.gts.types.IllegalAuthorityFault illegalAuthorityFault, Throwable cause) {
        super(message, cause);
        this.illegalAuthorityFault = illegalAuthorityFault;
    }

    public org.cagrid.gts.types.IllegalAuthorityFault getFaultInfo() {
        return this.illegalAuthorityFault;
    }
}
