
package org.cagrid.gts.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-03T15:36:59.683-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidAuthorityFault", targetNamespace = "http://cagrid.nci.nih.gov/GTS/types")
public class InvalidAuthorityFaultFaultMessage extends Exception {
    
    private org.cagrid.gts.types.InvalidAuthorityFault invalidAuthorityFault;

    public InvalidAuthorityFaultFaultMessage() {
        super();
    }
    
    public InvalidAuthorityFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidAuthorityFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidAuthorityFaultFaultMessage(String message, org.cagrid.gts.types.InvalidAuthorityFault invalidAuthorityFault) {
        super(message);
        this.invalidAuthorityFault = invalidAuthorityFault;
    }

    public InvalidAuthorityFaultFaultMessage(String message, org.cagrid.gts.types.InvalidAuthorityFault invalidAuthorityFault, Throwable cause) {
        super(message, cause);
        this.invalidAuthorityFault = invalidAuthorityFault;
    }

    public org.cagrid.gts.types.InvalidAuthorityFault getFaultInfo() {
        return this.invalidAuthorityFault;
    }
}
