package org.cagrid.index.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.index.wsrf.stubs.BigIndexPortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2014-04-11T08:38:01.960-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "BigIndexService", 
                  wsdlLocation = "/schema/org/cagrid/index/big_index_service.wsdl",
                  targetNamespace = "http://mds.globus.org/bigindex/2008/11/24/service") 
public class BigIndexService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mds.globus.org/bigindex/2008/11/24/service", "BigIndexService");
    public final static QName BigIndexPortTypePort = new QName("http://mds.globus.org/bigindex/2008/11/24/service", "BigIndexPortTypePort");
    static {
        URL url = BigIndexService.class.getResource("/schema/org/cagrid/index/big_index_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BigIndexService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/index/big_index_service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BigIndexService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BigIndexService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BigIndexService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BigIndexPortType
     */
    @WebEndpoint(name = "BigIndexPortTypePort")
    public BigIndexPortType getBigIndexPortTypePort() {
        return super.getPort(BigIndexPortTypePort, BigIndexPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BigIndexPortType
     */
    @WebEndpoint(name = "BigIndexPortTypePort")
    public BigIndexPortType getBigIndexPortTypePort(WebServiceFeature... features) {
        return super.getPort(BigIndexPortTypePort, BigIndexPortType.class, features);
    }

}
