package org.cagrid.mms.wsrf.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cagrid.mms.wsrf.stubs.MetadataModelServicePortType;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2014-04-29T20:21:17.318-05:00
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "MetadataModelService", 
                  wsdlLocation = "/schema/org/cagrid/mms/MetadataModelService_service.wsdl",
                  targetNamespace = "http://mms.cagrid.org/MetadataModelService/service") 
public class MetadataModelService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mms.cagrid.org/MetadataModelService/service", "MetadataModelService");
    public final static QName MetadataModelServicePortTypePort = new QName("http://mms.cagrid.org/MetadataModelService/service", "MetadataModelServicePortTypePort");
    static {
        URL url = MetadataModelService.class.getResource("/schema/org/cagrid/mms/MetadataModelService_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(MetadataModelService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/schema/org/cagrid/mms/MetadataModelService_service.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public MetadataModelService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MetadataModelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetadataModelService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MetadataModelServicePortType
     */
    @WebEndpoint(name = "MetadataModelServicePortTypePort")
    public MetadataModelServicePortType getMetadataModelServicePortTypePort() {
        return super.getPort(MetadataModelServicePortTypePort, MetadataModelServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetadataModelServicePortType
     */
    @WebEndpoint(name = "MetadataModelServicePortTypePort")
    public MetadataModelServicePortType getMetadataModelServicePortTypePort(WebServiceFeature... features) {
        return super.getPort(MetadataModelServicePortTypePort, MetadataModelServicePortType.class, features);
    }

}
