
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cagrid.gme.wsrf.stubs;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.527-04:00
 * Generated source version: 2.6.3
 * 
 */

@WebService(
                      serviceName = "GlobalModelExchangeService",
                      portName = "GlobalModelExchangePortTypePort",
                      targetNamespace = "http://gme.cagrid.org/GlobalModelExchange/service",
                      wsdlLocation = "/schema/org/cagrid/gme/GlobalModelExchange_Service.wsdl",
                      endpointInterface = "org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType")
                      
public class GlobalModelExchangePortTypeImpl implements GlobalModelExchangePortType {

    private static final Logger LOG = Logger.getLogger(GlobalModelExchangePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getImportingXMLSchemaNamespaces(org.cagrid.gme.wsrf.stubs.GetImportingXMLSchemaNamespacesRequest  parameters )*
     */
    public GetImportingXMLSchemaNamespacesResponse getImportingXMLSchemaNamespaces(GetImportingXMLSchemaNamespacesRequest parameters) throws NoSuchNamespaceExistsFaultFaultMessage    {
        LOG.info("Executing operation getImportingXMLSchemaNamespaces");
        System.out.println(parameters);
        try {
            GetImportingXMLSchemaNamespacesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchNamespaceExistsFaultFaultMessage("NoSuchNamespaceExistsFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getImportedXMLSchemaNamespaces(org.cagrid.gme.wsrf.stubs.GetImportedXMLSchemaNamespacesRequest  parameters )*
     */
    public GetImportedXMLSchemaNamespacesResponse getImportedXMLSchemaNamespaces(GetImportedXMLSchemaNamespacesRequest parameters) throws NoSuchNamespaceExistsFaultFaultMessage    {
        LOG.info("Executing operation getImportedXMLSchemaNamespaces");
        System.out.println(parameters);
        try {
            GetImportedXMLSchemaNamespacesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchNamespaceExistsFaultFaultMessage("NoSuchNamespaceExistsFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#publishXMLSchemas(org.cagrid.gme.wsrf.stubs.PublishXMLSchemasRequest  parameters )*
     */
    public org.cagrid.gme.wsrf.stubs.PublishXMLSchemasResponse publishXMLSchemas(PublishXMLSchemasRequest parameters) throws InvalidSchemaSubmissionFaultFaultMessage    { 
        LOG.info("Executing operation publishXMLSchemas");
        System.out.println(parameters);
        try {
            org.cagrid.gme.wsrf.stubs.PublishXMLSchemasResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidSchemaSubmissionFaultFaultMessage("InvalidSchemaSubmissionFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties  getMultipleResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getMultipleResourceProperties");
        System.out.println(getMultipleResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest  parameters )*
     */
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters) { 
        LOG.info("Executing operation getServiceSecurityMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getXMLSchemaNamespaces(org.cagrid.gme.wsrf.stubs.GetXMLSchemaNamespacesRequest  parameters )*
     */
    public GetXMLSchemaNamespacesResponse getXMLSchemaNamespaces(GetXMLSchemaNamespacesRequest parameters) {
        LOG.info("Executing operation getXMLSchemaNamespaces");
        System.out.println(parameters);
        try {
            GetXMLSchemaNamespacesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getXMLSchema(org.cagrid.gme.wsrf.stubs.GetXMLSchemaRequest  parameters )*
     */
    public GetXMLSchemaResponse getXMLSchema(GetXMLSchemaRequest parameters) throws NoSuchNamespaceExistsFaultFaultMessage    {
        LOG.info("Executing operation getXMLSchema");
        System.out.println(parameters);
        try {
            GetXMLSchemaResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchNamespaceExistsFaultFaultMessage("NoSuchNamespaceExistsFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties  queryResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault    { 
        LOG.info("Executing operation queryResourceProperties");
        System.out.println(queryResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault("QueryEvaluationErrorFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault("InvalidQueryExpressionFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault("UnknownQueryExpressionDialectFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#getXMLSchemaAndDependencies(org.cagrid.gme.wsrf.stubs.GetXMLSchemaAndDependenciesRequest  parameters )*
     */
    public GetXMLSchemaAndDependenciesResponse getXMLSchemaAndDependencies(GetXMLSchemaAndDependenciesRequest parameters) throws NoSuchNamespaceExistsFaultFaultMessage    {
        LOG.info("Executing operation getXMLSchemaAndDependencies");
        System.out.println(parameters);
        try {
            GetXMLSchemaAndDependenciesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchNamespaceExistsFaultFaultMessage("NoSuchNamespaceExistsFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.gme.wsrf.stubs.GlobalModelExchangePortType#deleteXMLSchemas(org.cagrid.gme.wsrf.stubs.DeleteXMLSchemasRequest  parameters )*
     */
    public DeleteXMLSchemasResponse deleteXMLSchemas(DeleteXMLSchemasRequest parameters) throws NoSuchNamespaceExistsFaultFaultMessage , UnableToDeleteSchemaFaultFaultMessage    {
        LOG.info("Executing operation deleteXMLSchemas");
        System.out.println(parameters);
        try {
            DeleteXMLSchemasResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NoSuchNamespaceExistsFaultFaultMessage("NoSuchNamespaceExistsFaultFaultMessage...");
        //throw new UnableToDeleteSchemaFaultFaultMessage("UnableToDeleteSchemaFaultFaultMessage...");
    }

}
