package org.cagrid.gme.wsrf.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.542-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", name = "GlobalModelExchangePortType")
@XmlSeeAlso({gov.nih.nci.cagrid.metadata.ObjectFactory.class, gov.nih.nci.cagrid.metadata.security.ObjectFactory.class, gov.nih.nci.cagrid.metadata.common.ObjectFactory.class, org.cagrid.gme.model.ObjectFactory.class, org.cagrid.gaards.security.servicesecurity.ObjectFactory.class, ObjectFactory.class, org.cagrid.gme.types.ObjectFactory.class, org.xmlsoap.schemas.ws._2004._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class, gov.nih.nci.cagrid.metadata.service.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GlobalModelExchangePortType {

    @WebResult(name = "GetImportingXMLSchemaNamespacesResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/GetImportingXMLSchemaNamespacesRequest")
    public GetImportingXMLSchemaNamespacesResponse getImportingXMLSchemaNamespaces(
            @WebParam(partName = "parameters", name = "GetImportingXMLSchemaNamespacesRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            GetImportingXMLSchemaNamespacesRequest parameters
    ) throws NoSuchNamespaceExistsFaultFaultMessage;

    @WebResult(name = "GetImportedXMLSchemaNamespacesResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/GetImportedXMLSchemaNamespacesRequest")
    public GetImportedXMLSchemaNamespacesResponse getImportedXMLSchemaNamespaces(
            @WebParam(partName = "parameters", name = "GetImportedXMLSchemaNamespacesRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            GetImportedXMLSchemaNamespacesRequest parameters
    ) throws NoSuchNamespaceExistsFaultFaultMessage;

    @WebResult(name = "PublishXMLSchemasResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/PublishXMLSchemasRequest")
    public PublishXMLSchemasResponse publishXMLSchemas(
            @WebParam(partName = "parameters", name = "PublishXMLSchemasRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            PublishXMLSchemasRequest parameters
    ) throws InvalidSchemaSubmissionFaultFaultMessage;

    @WebResult(name = "GetMultipleResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetMultipleResourcePropertiesResponse")
    @WebMethod(operationName = "GetMultipleResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetMultipleResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(
            @WebParam(partName = "GetMultipleResourcePropertiesRequest", name = "GetMultipleResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "GetServiceSecurityMetadataResponse", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity", partName = "parameters")
    @WebMethod(action = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity/GetServiceSecurityMetadataRequest")
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(
            @WebParam(partName = "parameters", name = "GetServiceSecurityMetadataRequest", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity")
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters
    );

    @WebResult(name = "GetXMLSchemaNamespacesResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/GetXMLSchemaNamespacesRequest")
    public GetXMLSchemaNamespacesResponse getXMLSchemaNamespaces(
            @WebParam(partName = "parameters", name = "GetXMLSchemaNamespacesRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            GetXMLSchemaNamespacesRequest parameters
    );

    @WebResult(name = "GetXMLSchemaResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/GetXMLSchemaRequest")
    public GetXMLSchemaResponse getXMLSchema(
            @WebParam(partName = "parameters", name = "GetXMLSchemaRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            GetXMLSchemaRequest parameters
    ) throws NoSuchNamespaceExistsFaultFaultMessage;

    @WebResult(name = "QueryResourcePropertiesResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "QueryResourcePropertiesResponse")
    @WebMethod(operationName = "QueryResourceProperties", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/QueryResourceProperties")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(
            @WebParam(partName = "QueryResourcePropertiesRequest", name = "QueryResourceProperties", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault;

    @WebResult(name = "GetResourcePropertyResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd", partName = "GetResourcePropertyResponse")
    @WebMethod(operationName = "GetResourceProperty", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetResourceProperty")
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(
            @WebParam(partName = "GetResourcePropertyRequest", name = "GetResourceProperty", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd")
            javax.xml.namespace.QName getResourcePropertyRequest
    ) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault;

    @WebResult(name = "GetXMLSchemaAndDependenciesResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/GetXMLSchemaAndDependenciesRequest")
    public GetXMLSchemaAndDependenciesResponse getXMLSchemaAndDependencies(
            @WebParam(partName = "parameters", name = "GetXMLSchemaAndDependenciesRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            GetXMLSchemaAndDependenciesRequest parameters
    ) throws NoSuchNamespaceExistsFaultFaultMessage;

    @WebResult(name = "DeleteXMLSchemasResponse", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange", partName = "parameters")
    @WebMethod(action = "http://gme.cagrid.org/GlobalModelExchange/DeleteXMLSchemasRequest")
    public DeleteXMLSchemasResponse deleteXMLSchemas(
            @WebParam(partName = "parameters", name = "DeleteXMLSchemasRequest", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange")
            DeleteXMLSchemasRequest parameters
    ) throws NoSuchNamespaceExistsFaultFaultMessage, UnableToDeleteSchemaFaultFaultMessage;
}
