
package org.cagrid.gme.wsrf.stubs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.cagrid.gme.wsrf.service.GlobalModelExchangeService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.439-04:00
 * Generated source version: 2.6.3
 * 
 */
public final class GlobalModelExchangePortType_GlobalModelExchangePortTypePort_Client {

    private static final QName SERVICE_NAME = new QName("http://gme.cagrid.org/GlobalModelExchange/service", "GlobalModelExchangeService");

    private GlobalModelExchangePortType_GlobalModelExchangePortTypePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GlobalModelExchangeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GlobalModelExchangeService ss = new GlobalModelExchangeService(wsdlURL, SERVICE_NAME);
        GlobalModelExchangePortType port = ss.getGlobalModelExchangePortTypePort();  
        
        {
        System.out.println("Invoking getImportingXMLSchemaNamespaces...");
        GetImportingXMLSchemaNamespacesRequest _getImportingXMLSchemaNamespaces_parameters = null;
        try {
            GetImportingXMLSchemaNamespacesResponse _getImportingXMLSchemaNamespaces__return = port.getImportingXMLSchemaNamespaces(_getImportingXMLSchemaNamespaces_parameters);
            System.out.println("getImportingXMLSchemaNamespaces.result=" + _getImportingXMLSchemaNamespaces__return);

        } catch (NoSuchNamespaceExistsFaultFaultMessage e) { 
            System.out.println("Expected exception: NoSuchNamespaceExistsFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getImportedXMLSchemaNamespaces...");
        GetImportedXMLSchemaNamespacesRequest _getImportedXMLSchemaNamespaces_parameters = null;
        try {
            GetImportedXMLSchemaNamespacesResponse _getImportedXMLSchemaNamespaces__return = port.getImportedXMLSchemaNamespaces(_getImportedXMLSchemaNamespaces_parameters);
            System.out.println("getImportedXMLSchemaNamespaces.result=" + _getImportedXMLSchemaNamespaces__return);

        } catch (NoSuchNamespaceExistsFaultFaultMessage e) { 
            System.out.println("Expected exception: NoSuchNamespaceExistsFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking publishXMLSchemas...");
        org.cagrid.gme.wsrf.stubs.PublishXMLSchemasRequest _publishXMLSchemas_parameters = null;
        try {
            org.cagrid.gme.wsrf.stubs.PublishXMLSchemasResponse _publishXMLSchemas__return = port.publishXMLSchemas(_publishXMLSchemas_parameters);
            System.out.println("publishXMLSchemas.result=" + _publishXMLSchemas__return);

        } catch (InvalidSchemaSubmissionFaultFaultMessage e) { 
            System.out.println("Expected exception: InvalidSchemaSubmissionFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getMultipleResourceProperties...");
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties _getMultipleResourceProperties_getMultipleResourcePropertiesRequest = null;
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _getMultipleResourceProperties__return = port.getMultipleResourceProperties(_getMultipleResourceProperties_getMultipleResourcePropertiesRequest);
            System.out.println("getMultipleResourceProperties.result=" + _getMultipleResourceProperties__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getServiceSecurityMetadata...");
        org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest _getServiceSecurityMetadata_parameters = null;
        org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _getServiceSecurityMetadata__return = port.getServiceSecurityMetadata(_getServiceSecurityMetadata_parameters);
        System.out.println("getServiceSecurityMetadata.result=" + _getServiceSecurityMetadata__return);


        }
        {
        System.out.println("Invoking getXMLSchemaNamespaces...");
        GetXMLSchemaNamespacesRequest _getXMLSchemaNamespaces_parameters = null;
        GetXMLSchemaNamespacesResponse _getXMLSchemaNamespaces__return = port.getXMLSchemaNamespaces(_getXMLSchemaNamespaces_parameters);
        System.out.println("getXMLSchemaNamespaces.result=" + _getXMLSchemaNamespaces__return);


        }
        {
        System.out.println("Invoking getXMLSchema...");
        GetXMLSchemaRequest _getXMLSchema_parameters = null;
        try {
            GetXMLSchemaResponse _getXMLSchema__return = port.getXMLSchema(_getXMLSchema_parameters);
            System.out.println("getXMLSchema.result=" + _getXMLSchema__return);

        } catch (NoSuchNamespaceExistsFaultFaultMessage e) { 
            System.out.println("Expected exception: NoSuchNamespaceExistsFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryResourceProperties...");
        org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties _queryResourceProperties_queryResourcePropertiesRequest = null;
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _queryResourceProperties__return = port.queryResourceProperties(_queryResourceProperties_queryResourcePropertiesRequest);
            System.out.println("queryResourceProperties.result=" + _queryResourceProperties__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault e) { 
            System.out.println("Expected exception: QueryEvaluationErrorFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault e) { 
            System.out.println("Expected exception: InvalidQueryExpressionFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault e) { 
            System.out.println("Expected exception: UnknownQueryExpressionDialectFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getResourceProperty...");
        QName _getResourceProperty_getResourcePropertyRequest = new QName("", "");
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _getResourceProperty__return = port.getResourceProperty(_getResourceProperty_getResourcePropertyRequest);
            System.out.println("getResourceProperty.result=" + _getResourceProperty__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getXMLSchemaAndDependencies...");
        GetXMLSchemaAndDependenciesRequest _getXMLSchemaAndDependencies_parameters = null;
        try {
            GetXMLSchemaAndDependenciesResponse _getXMLSchemaAndDependencies__return = port.getXMLSchemaAndDependencies(_getXMLSchemaAndDependencies_parameters);
            System.out.println("getXMLSchemaAndDependencies.result=" + _getXMLSchemaAndDependencies__return);

        } catch (NoSuchNamespaceExistsFaultFaultMessage e) { 
            System.out.println("Expected exception: NoSuchNamespaceExistsFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteXMLSchemas...");
        DeleteXMLSchemasRequest _deleteXMLSchemas_parameters = null;
        try {
            DeleteXMLSchemasResponse _deleteXMLSchemas__return = port.deleteXMLSchemas(_deleteXMLSchemas_parameters);
            System.out.println("deleteXMLSchemas.result=" + _deleteXMLSchemas__return);

        } catch (NoSuchNamespaceExistsFaultFaultMessage e) { 
            System.out.println("Expected exception: NoSuchNamespaceExistsFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (UnableToDeleteSchemaFaultFaultMessage e) { 
            System.out.println("Expected exception: UnableToDeleteSchemaFaultFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
