
package org.cagrid.gme.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.489-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidSchemaSubmissionFault", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange/types")
public class InvalidSchemaSubmissionFaultFaultMessage extends Exception {
    
    private org.cagrid.gme.types.InvalidSchemaSubmissionFault invalidSchemaSubmissionFault;

    public InvalidSchemaSubmissionFaultFaultMessage() {
        super();
    }
    
    public InvalidSchemaSubmissionFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidSchemaSubmissionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSchemaSubmissionFaultFaultMessage(String message, org.cagrid.gme.types.InvalidSchemaSubmissionFault invalidSchemaSubmissionFault) {
        super(message);
        this.invalidSchemaSubmissionFault = invalidSchemaSubmissionFault;
    }

    public InvalidSchemaSubmissionFaultFaultMessage(String message, org.cagrid.gme.types.InvalidSchemaSubmissionFault invalidSchemaSubmissionFault, Throwable cause) {
        super(message, cause);
        this.invalidSchemaSubmissionFault = invalidSchemaSubmissionFault;
    }

    public org.cagrid.gme.types.InvalidSchemaSubmissionFault getFaultInfo() {
        return this.invalidSchemaSubmissionFault;
    }
}
