
package org.cagrid.gme.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.482-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "NoSuchNamespaceExistsFault", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange/types")
public class NoSuchNamespaceExistsFaultFaultMessage extends Exception {
    
    private org.cagrid.gme.types.NoSuchNamespaceExistsFault noSuchNamespaceExistsFault;

    public NoSuchNamespaceExistsFaultFaultMessage() {
        super();
    }
    
    public NoSuchNamespaceExistsFaultFaultMessage(String message) {
        super(message);
    }
    
    public NoSuchNamespaceExistsFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchNamespaceExistsFaultFaultMessage(String message, org.cagrid.gme.types.NoSuchNamespaceExistsFault noSuchNamespaceExistsFault) {
        super(message);
        this.noSuchNamespaceExistsFault = noSuchNamespaceExistsFault;
    }

    public NoSuchNamespaceExistsFaultFaultMessage(String message, org.cagrid.gme.types.NoSuchNamespaceExistsFault noSuchNamespaceExistsFault, Throwable cause) {
        super(message, cause);
        this.noSuchNamespaceExistsFault = noSuchNamespaceExistsFault;
    }

    public org.cagrid.gme.types.NoSuchNamespaceExistsFault getFaultInfo() {
        return this.noSuchNamespaceExistsFault;
    }
}
