
package org.cagrid.gme.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-12T15:14:46.522-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "UnableToDeleteSchemaFault", targetNamespace = "http://gme.cagrid.org/GlobalModelExchange/types")
public class UnableToDeleteSchemaFaultFaultMessage extends Exception {
    
    private org.cagrid.gme.types.UnableToDeleteSchemaFault unableToDeleteSchemaFault;

    public UnableToDeleteSchemaFaultFaultMessage() {
        super();
    }
    
    public UnableToDeleteSchemaFaultFaultMessage(String message) {
        super(message);
    }
    
    public UnableToDeleteSchemaFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToDeleteSchemaFaultFaultMessage(String message, org.cagrid.gme.types.UnableToDeleteSchemaFault unableToDeleteSchemaFault) {
        super(message);
        this.unableToDeleteSchemaFault = unableToDeleteSchemaFault;
    }

    public UnableToDeleteSchemaFaultFaultMessage(String message, org.cagrid.gme.types.UnableToDeleteSchemaFault unableToDeleteSchemaFault, Throwable cause) {
        super(message, cause);
        this.unableToDeleteSchemaFault = unableToDeleteSchemaFault;
    }

    public org.cagrid.gme.types.UnableToDeleteSchemaFault getFaultInfo() {
        return this.unableToDeleteSchemaFault;
    }
}
