
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.066-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "GrantPrivilegeFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class GrantPrivilegeFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.GrantPrivilegeFault grantPrivilegeFault;

    public GrantPrivilegeFaultFaultMessage() {
        super();
    }
    
    public GrantPrivilegeFaultFaultMessage(String message) {
        super(message);
    }
    
    public GrantPrivilegeFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public GrantPrivilegeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GrantPrivilegeFault grantPrivilegeFault) {
        super(message);
        this.grantPrivilegeFault = grantPrivilegeFault;
    }

    public GrantPrivilegeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GrantPrivilegeFault grantPrivilegeFault, Throwable cause) {
        super(message, cause);
        this.grantPrivilegeFault = grantPrivilegeFault;
    }

    public org.cagrid.gridgrouper.types.GrantPrivilegeFault getFaultInfo() {
        return this.grantPrivilegeFault;
    }
}
