
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.027-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "GridGrouperRuntimeFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class GridGrouperRuntimeFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.GridGrouperRuntimeFault gridGrouperRuntimeFault;

    public GridGrouperRuntimeFaultFaultMessage() {
        super();
    }
    
    public GridGrouperRuntimeFaultFaultMessage(String message) {
        super(message);
    }
    
    public GridGrouperRuntimeFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public GridGrouperRuntimeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GridGrouperRuntimeFault gridGrouperRuntimeFault) {
        super(message);
        this.gridGrouperRuntimeFault = gridGrouperRuntimeFault;
    }

    public GridGrouperRuntimeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GridGrouperRuntimeFault gridGrouperRuntimeFault, Throwable cause) {
        super(message, cause);
        this.gridGrouperRuntimeFault = gridGrouperRuntimeFault;
    }

    public org.cagrid.gridgrouper.types.GridGrouperRuntimeFault getFaultInfo() {
        return this.gridGrouperRuntimeFault;
    }
}
