
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.127-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "GroupDeleteFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class GroupDeleteFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.GroupDeleteFault groupDeleteFault;

    public GroupDeleteFaultFaultMessage() {
        super();
    }
    
    public GroupDeleteFaultFaultMessage(String message) {
        super(message);
    }
    
    public GroupDeleteFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public GroupDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GroupDeleteFault groupDeleteFault) {
        super(message);
        this.groupDeleteFault = groupDeleteFault;
    }

    public GroupDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GroupDeleteFault groupDeleteFault, Throwable cause) {
        super(message, cause);
        this.groupDeleteFault = groupDeleteFault;
    }

    public org.cagrid.gridgrouper.types.GroupDeleteFault getFaultInfo() {
        return this.groupDeleteFault;
    }
}
