
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.020-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "GroupNotFoundFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class GroupNotFoundFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.GroupNotFoundFault groupNotFoundFault;

    public GroupNotFoundFaultFaultMessage() {
        super();
    }
    
    public GroupNotFoundFaultFaultMessage(String message) {
        super(message);
    }
    
    public GroupNotFoundFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public GroupNotFoundFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GroupNotFoundFault groupNotFoundFault) {
        super(message);
        this.groupNotFoundFault = groupNotFoundFault;
    }

    public GroupNotFoundFaultFaultMessage(String message, org.cagrid.gridgrouper.types.GroupNotFoundFault groupNotFoundFault, Throwable cause) {
        super(message, cause);
        this.groupNotFoundFault = groupNotFoundFault;
    }

    public org.cagrid.gridgrouper.types.GroupNotFoundFault getFaultInfo() {
        return this.groupNotFoundFault;
    }
}
