
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.038-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InsufficientPrivilegeFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class InsufficientPrivilegeFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.InsufficientPrivilegeFault insufficientPrivilegeFault;

    public InsufficientPrivilegeFaultFaultMessage() {
        super();
    }
    
    public InsufficientPrivilegeFaultFaultMessage(String message) {
        super(message);
    }
    
    public InsufficientPrivilegeFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InsufficientPrivilegeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.InsufficientPrivilegeFault insufficientPrivilegeFault) {
        super(message);
        this.insufficientPrivilegeFault = insufficientPrivilegeFault;
    }

    public InsufficientPrivilegeFaultFaultMessage(String message, org.cagrid.gridgrouper.types.InsufficientPrivilegeFault insufficientPrivilegeFault, Throwable cause) {
        super(message, cause);
        this.insufficientPrivilegeFault = insufficientPrivilegeFault;
    }

    public org.cagrid.gridgrouper.types.InsufficientPrivilegeFault getFaultInfo() {
        return this.insufficientPrivilegeFault;
    }
}
