
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.044-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "MemberAddFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class MemberAddFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.MemberAddFault memberAddFault;

    public MemberAddFaultFaultMessage() {
        super();
    }
    
    public MemberAddFaultFaultMessage(String message) {
        super(message);
    }
    
    public MemberAddFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public MemberAddFaultFaultMessage(String message, org.cagrid.gridgrouper.types.MemberAddFault memberAddFault) {
        super(message);
        this.memberAddFault = memberAddFault;
    }

    public MemberAddFaultFaultMessage(String message, org.cagrid.gridgrouper.types.MemberAddFault memberAddFault, Throwable cause) {
        super(message, cause);
        this.memberAddFault = memberAddFault;
    }

    public org.cagrid.gridgrouper.types.MemberAddFault getFaultInfo() {
        return this.memberAddFault;
    }
}
