
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.081-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "MemberDeleteFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class MemberDeleteFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.MemberDeleteFault memberDeleteFault;

    public MemberDeleteFaultFaultMessage() {
        super();
    }
    
    public MemberDeleteFaultFaultMessage(String message) {
        super(message);
    }
    
    public MemberDeleteFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public MemberDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.MemberDeleteFault memberDeleteFault) {
        super(message);
        this.memberDeleteFault = memberDeleteFault;
    }

    public MemberDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.MemberDeleteFault memberDeleteFault, Throwable cause) {
        super(message, cause);
        this.memberDeleteFault = memberDeleteFault;
    }

    public org.cagrid.gridgrouper.types.MemberDeleteFault getFaultInfo() {
        return this.memberDeleteFault;
    }
}
