
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.087-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "StemDeleteFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class StemDeleteFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.StemDeleteFault stemDeleteFault;

    public StemDeleteFaultFaultMessage() {
        super();
    }
    
    public StemDeleteFaultFaultMessage(String message) {
        super(message);
    }
    
    public StemDeleteFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StemDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemDeleteFault stemDeleteFault) {
        super(message);
        this.stemDeleteFault = stemDeleteFault;
    }

    public StemDeleteFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemDeleteFault stemDeleteFault, Throwable cause) {
        super(message, cause);
        this.stemDeleteFault = stemDeleteFault;
    }

    public org.cagrid.gridgrouper.types.StemDeleteFault getFaultInfo() {
        return this.stemDeleteFault;
    }
}
