
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.060-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "StemModifyFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class StemModifyFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.StemModifyFault stemModifyFault;

    public StemModifyFaultFaultMessage() {
        super();
    }
    
    public StemModifyFaultFaultMessage(String message) {
        super(message);
    }
    
    public StemModifyFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StemModifyFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemModifyFault stemModifyFault) {
        super(message);
        this.stemModifyFault = stemModifyFault;
    }

    public StemModifyFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemModifyFault stemModifyFault, Throwable cause) {
        super(message, cause);
        this.stemModifyFault = stemModifyFault;
    }

    public org.cagrid.gridgrouper.types.StemModifyFault getFaultInfo() {
        return this.stemModifyFault;
    }
}
