
package org.cagrid.gridgrouper.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-13T14:22:39.033-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "StemNotFoundFault", targetNamespace = "http://cagrid.nci.nih.gov/GridGrouper/types")
public class StemNotFoundFaultFaultMessage extends Exception {
    
    private org.cagrid.gridgrouper.types.StemNotFoundFault stemNotFoundFault;

    public StemNotFoundFaultFaultMessage() {
        super();
    }
    
    public StemNotFoundFaultFaultMessage(String message) {
        super(message);
    }
    
    public StemNotFoundFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StemNotFoundFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemNotFoundFault stemNotFoundFault) {
        super(message);
        this.stemNotFoundFault = stemNotFoundFault;
    }

    public StemNotFoundFaultFaultMessage(String message, org.cagrid.gridgrouper.types.StemNotFoundFault stemNotFoundFault, Throwable cause) {
        super(message, cause);
        this.stemNotFoundFault = stemNotFoundFault;
    }

    public org.cagrid.gridgrouper.types.StemNotFoundFault getFaultInfo() {
        return this.stemNotFoundFault;
    }
}
