
package org.cagrid.delegatedcredential.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:48.073-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "DelegationFault", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/types")
public class DelegationFaultFaultMessage extends Exception {
    
    private org.cagrid.cds.types.DelegationFault delegationFault;

    public DelegationFaultFaultMessage() {
        super();
    }
    
    public DelegationFaultFaultMessage(String message) {
        super(message);
    }
    
    public DelegationFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public DelegationFaultFaultMessage(String message, org.cagrid.cds.types.DelegationFault delegationFault) {
        super(message);
        this.delegationFault = delegationFault;
    }

    public DelegationFaultFaultMessage(String message, org.cagrid.cds.types.DelegationFault delegationFault, Throwable cause) {
        super(message, cause);
        this.delegationFault = delegationFault;
    }

    public org.cagrid.cds.types.DelegationFault getFaultInfo() {
        return this.delegationFault;
    }
}
