package org.cagrid.delegatedcredential.wsrf.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:48.092-04:00
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential", name = "DelegatedCredentialPortType")
@XmlSeeAlso({gov.nih.nci.cagrid.metadata.ObjectFactory.class, org.cagrid.gaards.security.servicesecurity.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.ObjectFactory.class, org.xmlsoap.schemas.ws._2004._03.addressing.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_basefaults_1_2_draft_01.ObjectFactory.class, org.cagrid.delegatedcredential.types.ObjectFactory.class, gov.nih.nci.cagrid.metadata.security.ObjectFactory.class, org.cagrid.cds.model.ObjectFactory.class, gov.nih.nci.cagrid.metadata.common.ObjectFactory.class, ObjectFactory.class, org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ObjectFactory.class, org.cagrid.cds.types.ObjectFactory.class, gov.nih.nci.cagrid.metadata.service.ObjectFactory.class, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01.ObjectFactory.class})
public interface DelegatedCredentialPortType {

    @RequestWrapper(localName = "Destroy", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", className = "org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01.Destroy")
    @WebMethod(operationName = "Destroy", action = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime/Destroy")
    @ResponseWrapper(localName = "DestroyResponse", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", className = "org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01.DestroyResponse")
    public void destroy() throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceNotDestroyedFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetServiceSecurityMetadataResponse", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity", partName = "parameters")
    @WebMethod(action = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity/GetServiceSecurityMetadataRequest")
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(
            @WebParam(partName = "parameters", name = "GetServiceSecurityMetadataRequest", targetNamespace = "http://security.introduce.cagrid.nci.nih.gov/ServiceSecurity")
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetDelegatedCredentialResponse", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential", partName = "parameters")
    @WebMethod(action = "http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/GetDelegatedCredentialRequest")
    public GetDelegatedCredentialResponse getDelegatedCredential(
            @WebParam(partName = "parameters", name = "GetDelegatedCredentialRequest", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential")
            GetDelegatedCredentialRequest parameters
    ) throws DelegationFaultFaultMessage, PermissionDeniedFaultFaultMessage, CDSInternalFaultFaultMessage;
}
