
package org.cagrid.delegatedcredential.wsrf.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-05-06T17:03:48.076-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "PermissionDeniedFault", targetNamespace = "http://cds.gaards.cagrid.org/CredentialDelegationService/types")
public class PermissionDeniedFaultFaultMessage extends Exception {
    
    private org.cagrid.cds.types.PermissionDeniedFault permissionDeniedFault;

    public PermissionDeniedFaultFaultMessage() {
        super();
    }
    
    public PermissionDeniedFaultFaultMessage(String message) {
        super(message);
    }
    
    public PermissionDeniedFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public PermissionDeniedFaultFaultMessage(String message, org.cagrid.cds.types.PermissionDeniedFault permissionDeniedFault) {
        super(message);
        this.permissionDeniedFault = permissionDeniedFault;
    }

    public PermissionDeniedFaultFaultMessage(String message, org.cagrid.cds.types.PermissionDeniedFault permissionDeniedFault, Throwable cause) {
        super(message, cause);
        this.permissionDeniedFault = permissionDeniedFault;
    }

    public org.cagrid.cds.types.PermissionDeniedFault getFaultInfo() {
        return this.permissionDeniedFault;
    }
}
