
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-10T14:11:33.209-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "DorianInternalFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class DorianInternalFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.DorianInternalFault dorianInternalFault;

    public DorianInternalFaultFaultMessage() {
        super();
    }
    
    public DorianInternalFaultFaultMessage(String message) {
        super(message);
    }
    
    public DorianInternalFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public DorianInternalFaultFaultMessage(String message, org.cagrid.dorian.types.DorianInternalFault dorianInternalFault) {
        super(message);
        this.dorianInternalFault = dorianInternalFault;
    }

    public DorianInternalFaultFaultMessage(String message, org.cagrid.dorian.types.DorianInternalFault dorianInternalFault, Throwable cause) {
        super(message, cause);
        this.dorianInternalFault = dorianInternalFault;
    }

    public org.cagrid.dorian.types.DorianInternalFault getFaultInfo() {
        return this.dorianInternalFault;
    }
}
