
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cagrid.dorian;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.902-04:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "DorianService",
                      portName = "DorianPortTypePort",
                      targetNamespace = "http://cagrid.nci.nih.gov/Dorian/service",
                      wsdlLocation = "/schema/org/cagrid/dorian/Dorian_Service.wsdl",
                      endpointInterface = "org.cagrid.dorian.DorianPortType")
                      
public class DorianPortTypeImpl implements DorianPortType {

    private static final Logger LOG = Logger.getLogger(DorianPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties  getMultipleResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourceProperties getMultipleResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getMultipleResourceProperties");
        System.out.println(getMultipleResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetMultipleResourcePropertiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#setPublish(org.cagrid.dorian.SetPublishRequest  parameters )*
     */
    public org.cagrid.dorian.SetPublishResponse setPublish(SetPublishRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidTrustedIdPFaultFaultMessage    { 
        LOG.info("Executing operation setPublish");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.SetPublishResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidTrustedIdPFaultFaultMessage("InvalidTrustedIdPFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getPublish(org.cagrid.dorian.GetPublishRequest  parameters )*
     */
    public org.cagrid.dorian.GetPublishResponse getPublish(GetPublishRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidTrustedIdPFaultFaultMessage    { 
        LOG.info("Executing operation getPublish");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetPublishResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidTrustedIdPFaultFaultMessage("InvalidTrustedIdPFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateTrustedIdP(org.cagrid.dorian.UpdateTrustedIdPRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateTrustedIdPResponse updateTrustedIdP(UpdateTrustedIdPRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidTrustedIdPFaultFaultMessage    { 
        LOG.info("Executing operation updateTrustedIdP");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateTrustedIdPResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidTrustedIdPFaultFaultMessage("InvalidTrustedIdPFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getTrustedIdPs(org.cagrid.dorian.GetTrustedIdPsRequest  parameters )*
     */
    public org.cagrid.dorian.GetTrustedIdPsResponse getTrustedIdPs(GetTrustedIdPsRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getTrustedIdPs");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetTrustedIdPsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#performFederationAudit(org.cagrid.dorian.PerformFederationAuditRequest  parameters )*
     */
    public org.cagrid.dorian.PerformFederationAuditResponse performFederationAudit(PerformFederationAuditRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation performFederationAudit");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.PerformFederationAuditResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#findUserCertificates(org.cagrid.dorian.FindUserCertificatesRequest  parameters )*
     */
    public org.cagrid.dorian.FindUserCertificatesResponse findUserCertificates(FindUserCertificatesRequest parameters) throws DorianInternalFaultFaultMessage , InvalidUserCertificateFaultFaultMessage , PermissionDeniedFaultFaultMessage    { 
        LOG.info("Executing operation findUserCertificates");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.FindUserCertificatesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserCertificateFaultFaultMessage("InvalidUserCertificateFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#findGridUsers(org.cagrid.dorian.FindGridUsersRequest  parameters )*
     */
    public org.cagrid.dorian.FindGridUsersResponse findGridUsers(FindGridUsersRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation findGridUsers");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.FindGridUsersResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#authenticateUser(org.cagrid.gaards.authentication.AuthenticateUserRequest  parameters )*
     */
    public org.cagrid.gaards.authentication.AuthenticateUserResponse authenticateUser(org.cagrid.gaards.authentication.AuthenticateUserRequest parameters) throws org.cagrid.gaards.authentication.InsufficientAttributeFaultFaultMessage , org.cagrid.gaards.authentication.AuthenticationProviderFaultFaultMessage , org.cagrid.gaards.authentication.InvalidCredentialFaultFaultMessage , org.cagrid.gaards.authentication.CredentialNotSupportedFaultFaultMessage    { 
        LOG.info("Executing operation authenticateUser");
        System.out.println(parameters);
        try {
            org.cagrid.gaards.authentication.AuthenticateUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.cagrid.gaards.authentication.InsufficientAttributeFaultFaultMessage("InsufficientAttributeFaultFaultMessage...");
        //throw new org.cagrid.gaards.authentication.AuthenticationProviderFaultFaultMessage("AuthenticationProviderFaultFaultMessage...");
        //throw new org.cagrid.gaards.authentication.InvalidCredentialFaultFaultMessage("InvalidCredentialFaultFaultMessage...");
        //throw new org.cagrid.gaards.authentication.CredentialNotSupportedFaultFaultMessage("CredentialNotSupportedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#findLocalUsers(org.cagrid.dorian.FindLocalUsersRequest  parameters )*
     */
    public org.cagrid.dorian.FindLocalUsersResponse findLocalUsers(FindLocalUsersRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation findLocalUsers");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.FindLocalUsersResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#requestHostCertificate(org.cagrid.dorian.RequestHostCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.RequestHostCertificateResponse requestHostCertificate(RequestHostCertificateRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidHostCertificateRequestFaultFaultMessage , InvalidHostCertificateFaultFaultMessage    { 
        LOG.info("Executing operation requestHostCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RequestHostCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidHostCertificateRequestFaultFaultMessage("InvalidHostCertificateRequestFaultFaultMessage...");
        //throw new InvalidHostCertificateFaultFaultMessage("InvalidHostCertificateFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getOwnedHostCertificates(org.cagrid.dorian.GetOwnedHostCertificatesRequest  parameters )*
     */
    public org.cagrid.dorian.GetOwnedHostCertificatesResponse getOwnedHostCertificates(GetOwnedHostCertificatesRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getOwnedHostCertificates");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetOwnedHostCertificatesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getAccountProfile(org.cagrid.dorian.GetAccountProfileRequest  parameters )*
     */
    public org.cagrid.dorian.GetAccountProfileResponse getAccountProfile(GetAccountProfileRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getAccountProfile");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetAccountProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getGridUserPolicies(org.cagrid.dorian.GetGridUserPoliciesRequest  parameters )*
     */
    public org.cagrid.dorian.GetGridUserPoliciesResponse getGridUserPolicies(GetGridUserPoliciesRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getGridUserPolicies");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetGridUserPoliciesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#userSearch(org.cagrid.dorian.UserSearchRequest  parameters )*
     */
    public org.cagrid.dorian.UserSearchResponse userSearch(UserSearchRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation userSearch");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UserSearchResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#hostSearch(org.cagrid.dorian.HostSearchRequest  parameters )*
     */
    public org.cagrid.dorian.HostSearchResponse hostSearch(HostSearchRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation hostSearch");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.HostSearchResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#addTrustedIdP(org.cagrid.dorian.AddTrustedIdPRequest  parameters )*
     */
    public org.cagrid.dorian.AddTrustedIdPResponse addTrustedIdP(AddTrustedIdPRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidTrustedIdPFaultFaultMessage    { 
        LOG.info("Executing operation addTrustedIdP");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.AddTrustedIdPResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidTrustedIdPFaultFaultMessage("InvalidTrustedIdPFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#registerWithIdP(org.cagrid.dorian.RegisterWithIdPRequest  parameters )*
     */
    public org.cagrid.dorian.RegisterWithIdPResponse registerWithIdP(RegisterWithIdPRequest parameters) throws DorianInternalFaultFaultMessage , InvalidUserPropertyFaultFaultMessage    { 
        LOG.info("Executing operation registerWithIdP");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RegisterWithIdPResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserPropertyFaultFaultMessage("InvalidUserPropertyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateGridUser(org.cagrid.dorian.UpdateGridUserRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateGridUserResponse updateGridUser(UpdateGridUserRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , InvalidUserFaultFaultMessage    { 
        LOG.info("Executing operation updateGridUser");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateGridUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new InvalidUserFaultFaultMessage("InvalidUserFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#removeUserCertificate(org.cagrid.dorian.RemoveUserCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.RemoveUserCertificateResponse removeUserCertificate(RemoveUserCertificateRequest parameters) throws DorianInternalFaultFaultMessage , InvalidUserCertificateFaultFaultMessage , PermissionDeniedFaultFaultMessage    { 
        LOG.info("Executing operation removeUserCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RemoveUserCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserCertificateFaultFaultMessage("InvalidUserCertificateFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#requestUserCertificate(org.cagrid.dorian.RequestUserCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.RequestUserCertificateResponse requestUserCertificate(RequestUserCertificateRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , InvalidAssertionFaultFaultMessage , UserPolicyFaultFaultMessage    { 
        LOG.info("Executing operation requestUserCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RequestUserCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new InvalidAssertionFaultFaultMessage("InvalidAssertionFaultFaultMessage...");
        //throw new UserPolicyFaultFaultMessage("UserPolicyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#removeTrustedIdP(org.cagrid.dorian.RemoveTrustedIdPRequest  parameters )*
     */
    public org.cagrid.dorian.RemoveTrustedIdPResponse removeTrustedIdP(RemoveTrustedIdPRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidTrustedIdPFaultFaultMessage    { 
        LOG.info("Executing operation removeTrustedIdP");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RemoveTrustedIdPResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidTrustedIdPFaultFaultMessage("InvalidTrustedIdPFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateLocalUser(org.cagrid.dorian.UpdateLocalUserRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateLocalUserResponse updateLocalUser(UpdateLocalUserRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , NoSuchUserFaultFaultMessage    { 
        LOG.info("Executing operation updateLocalUser");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateLocalUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new NoSuchUserFaultFaultMessage("NoSuchUserFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#changeLocalUserPassword(org.cagrid.dorian.ChangeLocalUserPasswordRequest  parameters )*
     */
    public org.cagrid.dorian.ChangeLocalUserPasswordResponse changeLocalUserPassword(ChangeLocalUserPasswordRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidUserPropertyFaultFaultMessage    { 
        LOG.info("Executing operation changeLocalUserPassword");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.ChangeLocalUserPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserPropertyFaultFaultMessage("InvalidUserPropertyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#removeLocalUser(org.cagrid.dorian.RemoveLocalUserRequest  parameters )*
     */
    public org.cagrid.dorian.RemoveLocalUserResponse removeLocalUser(RemoveLocalUserRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation removeLocalUser");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RemoveLocalUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getCACertificate(org.cagrid.dorian.GetCACertificateRequest  parameters )*
     */
    public org.cagrid.dorian.GetCACertificateResponse getCACertificate(GetCACertificateRequest parameters) throws DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getCACertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetCACertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#doesLocalUserExist(org.cagrid.dorian.DoesLocalUserExistRequest  parameters )*
     */
    public org.cagrid.dorian.DoesLocalUserExistResponse doesLocalUserExist(DoesLocalUserExistRequest parameters) throws DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation doesLocalUserExist");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.DoesLocalUserExistResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#performIdentityProviderAudit(org.cagrid.dorian.PerformIdentityProviderAuditRequest  parameters )*
     */
    public org.cagrid.dorian.PerformIdentityProviderAuditResponse performIdentityProviderAudit(PerformIdentityProviderAuditRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation performIdentityProviderAudit");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.PerformIdentityProviderAuditResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getAdmins(org.cagrid.dorian.GetAdminsRequest  parameters )*
     */
    public org.cagrid.dorian.GetAdminsResponse getAdmins(GetAdminsRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation getAdmins");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.GetAdminsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#approveHostCertificate(org.cagrid.dorian.ApproveHostCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.ApproveHostCertificateResponse approveHostCertificate(ApproveHostCertificateRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidHostCertificateFaultFaultMessage    { 
        LOG.info("Executing operation approveHostCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.ApproveHostCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidHostCertificateFaultFaultMessage("InvalidHostCertificateFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest  parameters )*
     */
    public org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse getServiceSecurityMetadata(org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataRequest parameters) { 
        LOG.info("Executing operation getServiceSecurityMetadata");
        System.out.println(parameters);
        try {
            org.cagrid.gaards.security.servicesecurity.GetServiceSecurityMetadataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties  queryResourcePropertiesRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse queryResourceProperties(org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourceProperties queryResourcePropertiesRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault    { 
        LOG.info("Executing operation queryResourceProperties");
        System.out.println(queryResourcePropertiesRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryResourcePropertiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.QueryEvaluationErrorFault("QueryEvaluationErrorFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidQueryExpressionFault("InvalidQueryExpressionFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.UnknownQueryExpressionDialectFault("UnknownQueryExpressionDialectFault...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateAccountProfile(org.cagrid.dorian.UpdateAccountProfileRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateAccountProfileResponse updateAccountProfile(UpdateAccountProfileRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , NoSuchUserFaultFaultMessage , InvalidUserPropertyFaultFaultMessage    { 
        LOG.info("Executing operation updateAccountProfile");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateAccountProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new NoSuchUserFaultFaultMessage("NoSuchUserFaultFaultMessage...");
        //throw new InvalidUserPropertyFaultFaultMessage("InvalidUserPropertyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#registerLocalUser(org.cagrid.dorian.RegisterLocalUserRequest  parameters )*
     */
    public org.cagrid.dorian.RegisterLocalUserResponse registerLocalUser(RegisterLocalUserRequest parameters) throws DorianInternalFaultFaultMessage , InvalidUserPropertyFaultFaultMessage    { 
        LOG.info("Executing operation registerLocalUser");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RegisterLocalUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserPropertyFaultFaultMessage("InvalidUserPropertyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#addAdmin(org.cagrid.dorian.AddAdminRequest  parameters )*
     */
    public org.cagrid.dorian.AddAdminResponse addAdmin(AddAdminRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation addAdmin");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.AddAdminResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#removeAdmin(org.cagrid.dorian.RemoveAdminRequest  parameters )*
     */
    public org.cagrid.dorian.RemoveAdminResponse removeAdmin(RemoveAdminRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation removeAdmin");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RemoveAdminResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#createProxy(org.cagrid.dorian.CreateProxyRequest  parameters )*
     */
    public org.cagrid.dorian.CreateProxyResponse createProxy(CreateProxyRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , InvalidAssertionFaultFaultMessage , UserPolicyFaultFaultMessage , InvalidProxyFaultFaultMessage    { 
        LOG.info("Executing operation createProxy");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.CreateProxyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new InvalidAssertionFaultFaultMessage("InvalidAssertionFaultFaultMessage...");
        //throw new UserPolicyFaultFaultMessage("UserPolicyFaultFaultMessage...");
        //throw new InvalidProxyFaultFaultMessage("InvalidProxyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateHostCertificateRecord(org.cagrid.dorian.UpdateHostCertificateRecordRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateHostCertificateRecordResponse updateHostCertificateRecord(UpdateHostCertificateRecordRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidHostCertificateFaultFaultMessage    { 
        LOG.info("Executing operation updateHostCertificateRecord");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateHostCertificateRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidHostCertificateFaultFaultMessage("InvalidHostCertificateFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#removeGridUser(org.cagrid.dorian.RemoveGridUserRequest  parameters )*
     */
    public org.cagrid.dorian.RemoveGridUserResponse removeGridUser(RemoveGridUserRequest parameters) throws DorianInternalFaultFaultMessage , PermissionDeniedFaultFaultMessage , InvalidUserFaultFaultMessage    { 
        LOG.info("Executing operation removeGridUser");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RemoveGridUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new InvalidUserFaultFaultMessage("InvalidUserFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#changeIdPUserPassword(org.cagrid.dorian.ChangeIdPUserPasswordRequest  parameters )*
     */
    public org.cagrid.dorian.ChangeIdPUserPasswordResponse changeIdPUserPassword(ChangeIdPUserPasswordRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidUserPropertyFaultFaultMessage    { 
        LOG.info("Executing operation changeIdPUserPassword");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.ChangeIdPUserPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserPropertyFaultFaultMessage("InvalidUserPropertyFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#updateUserCertificate(org.cagrid.dorian.UpdateUserCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.UpdateUserCertificateResponse updateUserCertificate(UpdateUserCertificateRequest parameters) throws DorianInternalFaultFaultMessage , InvalidUserCertificateFaultFaultMessage , PermissionDeniedFaultFaultMessage    { 
        LOG.info("Executing operation updateUserCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.UpdateUserCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidUserCertificateFaultFaultMessage("InvalidUserCertificateFaultFaultMessage...");
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#renewHostCertificate(org.cagrid.dorian.RenewHostCertificateRequest  parameters )*
     */
    public org.cagrid.dorian.RenewHostCertificateResponse renewHostCertificate(RenewHostCertificateRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage , InvalidHostCertificateFaultFaultMessage    { 
        LOG.info("Executing operation renewHostCertificate");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.RenewHostCertificateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
        //throw new InvalidHostCertificateFaultFaultMessage("InvalidHostCertificateFaultFaultMessage...");
    }

    /* (non-Javadoc)
     * @see org.cagrid.dorian.DorianPortType#findHostCertificates(org.cagrid.dorian.FindHostCertificatesRequest  parameters )*
     */
    public org.cagrid.dorian.FindHostCertificatesResponse findHostCertificates(FindHostCertificatesRequest parameters) throws PermissionDeniedFaultFaultMessage , DorianInternalFaultFaultMessage    { 
        LOG.info("Executing operation findHostCertificates");
        System.out.println(parameters);
        try {
            org.cagrid.dorian.FindHostCertificatesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PermissionDeniedFaultFaultMessage("PermissionDeniedFaultFaultMessage...");
        //throw new DorianInternalFaultFaultMessage("DorianInternalFaultFaultMessage...");
    }

}
