
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.786-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidHostCertificateRequestFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidHostCertificateRequestFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidHostCertificateRequestFault invalidHostCertificateRequestFault;

    public InvalidHostCertificateRequestFaultFaultMessage() {
        super();
    }
    
    public InvalidHostCertificateRequestFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidHostCertificateRequestFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidHostCertificateRequestFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidHostCertificateRequestFault invalidHostCertificateRequestFault) {
        super(message);
        this.invalidHostCertificateRequestFault = invalidHostCertificateRequestFault;
    }

    public InvalidHostCertificateRequestFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidHostCertificateRequestFault invalidHostCertificateRequestFault, Throwable cause) {
        super(message, cause);
        this.invalidHostCertificateRequestFault = invalidHostCertificateRequestFault;
    }

    public org.cagrid.dorian.types.InvalidHostCertificateRequestFault getFaultInfo() {
        return this.invalidHostCertificateRequestFault;
    }
}
