
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-10T14:11:33.343-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidUserPropertyFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidUserPropertyFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidUserPropertyFault invalidUserPropertyFault;

    public InvalidUserPropertyFaultFaultMessage() {
        super();
    }
    
    public InvalidUserPropertyFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidUserPropertyFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidUserPropertyFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidUserPropertyFault invalidUserPropertyFault) {
        super(message);
        this.invalidUserPropertyFault = invalidUserPropertyFault;
    }

    public InvalidUserPropertyFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidUserPropertyFault invalidUserPropertyFault, Throwable cause) {
        super(message, cause);
        this.invalidUserPropertyFault = invalidUserPropertyFault;
    }

    public org.cagrid.dorian.types.InvalidUserPropertyFault getFaultInfo() {
        return this.invalidUserPropertyFault;
    }
}
