
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.893-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidProxyFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidProxyFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidProxyFault invalidProxyFault;

    public InvalidProxyFaultFaultMessage() {
        super();
    }
    
    public InvalidProxyFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidProxyFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidProxyFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidProxyFault invalidProxyFault) {
        super(message);
        this.invalidProxyFault = invalidProxyFault;
    }

    public InvalidProxyFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidProxyFault invalidProxyFault, Throwable cause) {
        super(message, cause);
        this.invalidProxyFault = invalidProxyFault;
    }

    public org.cagrid.dorian.types.InvalidProxyFault getFaultInfo() {
        return this.invalidProxyFault;
    }
}
