
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.793-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidHostCertificateFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidHostCertificateFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidHostCertificateFault invalidHostCertificateFault;

    public InvalidHostCertificateFaultFaultMessage() {
        super();
    }
    
    public InvalidHostCertificateFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidHostCertificateFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidHostCertificateFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidHostCertificateFault invalidHostCertificateFault) {
        super(message);
        this.invalidHostCertificateFault = invalidHostCertificateFault;
    }

    public InvalidHostCertificateFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidHostCertificateFault invalidHostCertificateFault, Throwable cause) {
        super(message, cause);
        this.invalidHostCertificateFault = invalidHostCertificateFault;
    }

    public org.cagrid.dorian.types.InvalidHostCertificateFault getFaultInfo() {
        return this.invalidHostCertificateFault;
    }
}
