
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.827-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidAssertionFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidAssertionFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidAssertionFault invalidAssertionFault;

    public InvalidAssertionFaultFaultMessage() {
        super();
    }
    
    public InvalidAssertionFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidAssertionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidAssertionFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidAssertionFault invalidAssertionFault) {
        super(message);
        this.invalidAssertionFault = invalidAssertionFault;
    }

    public InvalidAssertionFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidAssertionFault invalidAssertionFault, Throwable cause) {
        super(message, cause);
        this.invalidAssertionFault = invalidAssertionFault;
    }

    public org.cagrid.dorian.types.InvalidAssertionFault getFaultInfo() {
        return this.invalidAssertionFault;
    }
}
