
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-10T14:11:33.235-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidUserCertificateFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidUserCertificateFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.model.exceptions.InvalidUserCertificateFault invalidUserCertificateFault;

    public InvalidUserCertificateFaultFaultMessage() {
        super();
    }
    
    public InvalidUserCertificateFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidUserCertificateFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidUserCertificateFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.InvalidUserCertificateFault invalidUserCertificateFault) {
        super(message);
        this.invalidUserCertificateFault = invalidUserCertificateFault;
    }

    public InvalidUserCertificateFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.InvalidUserCertificateFault invalidUserCertificateFault, Throwable cause) {
        super(message, cause);
        this.invalidUserCertificateFault = invalidUserCertificateFault;
    }

    public org.cagrid.dorian.model.exceptions.InvalidUserCertificateFault getFaultInfo() {
        return this.invalidUserCertificateFault;
    }
}
