
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.728-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "InvalidTrustedIdPFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class InvalidTrustedIdPFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.InvalidTrustedIdPFault invalidTrustedIdPFault;

    public InvalidTrustedIdPFaultFaultMessage() {
        super();
    }
    
    public InvalidTrustedIdPFaultFaultMessage(String message) {
        super(message);
    }
    
    public InvalidTrustedIdPFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTrustedIdPFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidTrustedIdPFault invalidTrustedIdPFault) {
        super(message);
        this.invalidTrustedIdPFault = invalidTrustedIdPFault;
    }

    public InvalidTrustedIdPFaultFaultMessage(String message, org.cagrid.dorian.types.InvalidTrustedIdPFault invalidTrustedIdPFault, Throwable cause) {
        super(message, cause);
        this.invalidTrustedIdPFault = invalidTrustedIdPFault;
    }

    public org.cagrid.dorian.types.InvalidTrustedIdPFault getFaultInfo() {
        return this.invalidTrustedIdPFault;
    }
}
