
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T14:19:02.850-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "NoSuchUserFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class NoSuchUserFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.types.NoSuchUserFault noSuchUserFault;

    public NoSuchUserFaultFaultMessage() {
        super();
    }
    
    public NoSuchUserFaultFaultMessage(String message) {
        super(message);
    }
    
    public NoSuchUserFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchUserFaultFaultMessage(String message, org.cagrid.dorian.types.NoSuchUserFault noSuchUserFault) {
        super(message);
        this.noSuchUserFault = noSuchUserFault;
    }

    public NoSuchUserFaultFaultMessage(String message, org.cagrid.dorian.types.NoSuchUserFault noSuchUserFault, Throwable cause) {
        super(message, cause);
        this.noSuchUserFault = noSuchUserFault;
    }

    public org.cagrid.dorian.types.NoSuchUserFault getFaultInfo() {
        return this.noSuchUserFault;
    }
}
