
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-10T14:11:33.199-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "PermissionDeniedFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class PermissionDeniedFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.model.exceptions.PermissionDeniedFault permissionDeniedFault;

    public PermissionDeniedFaultFaultMessage() {
        super();
    }
    
    public PermissionDeniedFaultFaultMessage(String message) {
        super(message);
    }
    
    public PermissionDeniedFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public PermissionDeniedFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.PermissionDeniedFault permissionDeniedFault) {
        super(message);
        this.permissionDeniedFault = permissionDeniedFault;
    }

    public PermissionDeniedFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.PermissionDeniedFault permissionDeniedFault, Throwable cause) {
        super(message, cause);
        this.permissionDeniedFault = permissionDeniedFault;
    }

    public org.cagrid.dorian.model.exceptions.PermissionDeniedFault getFaultInfo() {
        return this.permissionDeniedFault;
    }
}
