
package org.cagrid.dorian;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-06-10T14:11:33.381-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "UserPolicyFault", targetNamespace = "http://cagrid.nci.nih.gov/Dorian/types")
public class UserPolicyFaultFaultMessage extends Exception {
    
    private org.cagrid.dorian.model.exceptions.UserPolicyFault userPolicyFault;

    public UserPolicyFaultFaultMessage() {
        super();
    }
    
    public UserPolicyFaultFaultMessage(String message) {
        super(message);
    }
    
    public UserPolicyFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UserPolicyFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.UserPolicyFault userPolicyFault) {
        super(message);
        this.userPolicyFault = userPolicyFault;
    }

    public UserPolicyFaultFaultMessage(String message, org.cagrid.dorian.model.exceptions.UserPolicyFault userPolicyFault, Throwable cause) {
        super(message, cause);
        this.userPolicyFault = userPolicyFault;
    }

    public org.cagrid.dorian.model.exceptions.UserPolicyFault getFaultInfo() {
        return this.userPolicyFault;
    }
}
