<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BigIndex" targetNamespace="http://mds.globus.org/bigindex/2008/11/24/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://mds.globus.org/bigindex/2008/11/24/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://mds.globus.org/bigindex/2008/11/24/bindings" location="big_index_bindings.wsdl"/>
  <wsdl:service name="BigIndexService">
    <wsdl:port name="BigIndexPortTypePort" binding="binding:BigIndexPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
