<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CredentialDelegationService" targetNamespace="http://cds.gaards.cagrid.org/CredentialDelegationService/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:binding="http://cds.gaards.cagrid.org/CredentialDelegationService/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://cds.gaards.cagrid.org/CredentialDelegationService/bindings" location="CredentialDelegationService_bindings.wsdl"/>
  <wsdl:service name="CredentialDelegationService">
    <wsdl:port name="CredentialDelegationServicePortTypePort" binding="binding:CredentialDelegationServicePortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
