<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="DelegatedCredential" targetNamespace="http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:binding="http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://cds.gaards.cagrid.org/CredentialDelegationService/DelegatedCredential/bindings" location="DelegatedCredential_bindings.wsdl"/>
  <wsdl:service name="DelegatedCredentialService">
    <wsdl:port name="DelegatedCredentialPortTypePort" binding="binding:DelegatedCredentialPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
