
package org.cagrid.gaards.authentication;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-29T09:59:33.660-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "CredentialNotSupportedFault", targetNamespace = "http://gaards.cagrid.org/authentication-faults")
public class CredentialNotSupportedFaultFaultMessage extends Exception {
    
    private org.cagrid.gaards.authentication.faults.CredentialNotSupportedFault credentialNotSupportedFault;

    public CredentialNotSupportedFaultFaultMessage() {
        super();
    }
    
    public CredentialNotSupportedFaultFaultMessage(String message) {
        super(message);
    }
    
    public CredentialNotSupportedFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CredentialNotSupportedFaultFaultMessage(String message, org.cagrid.gaards.authentication.faults.CredentialNotSupportedFault credentialNotSupportedFault) {
        super(message);
        this.credentialNotSupportedFault = credentialNotSupportedFault;
    }

    public CredentialNotSupportedFaultFaultMessage(String message, org.cagrid.gaards.authentication.faults.CredentialNotSupportedFault credentialNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.credentialNotSupportedFault = credentialNotSupportedFault;
    }

    public org.cagrid.gaards.authentication.faults.CredentialNotSupportedFault getFaultInfo() {
        return this.credentialNotSupportedFault;
    }
}
